### ISSUE TITLE
Getting Meshtastic PLI on the paired EUD when using TAK_TRACKER

### ISSUE THREAD

**Issue by Manaberry** [meshtastic/Meshtastic-Android#1004]
Hi,

I've built two device with GNSS module. They both work fine but I would love to also be able to track my own position in ATAK while using TAK_TRACKER. For now, I only have the initial position when I turn on the device, but no position update are being used by the paired EUD in ATAK. I feel like it's odd as the position is being sent to the mesh anyway.

**Comment by thebentern** [comment]
TAK_TRACKER role sends out TAK PLI packets instead of Meshtastic position positions packets, so this behavior is expected. This role was not intended to be used in a client connected setting, but rather as standalone tracker devices meshing with devices connected to EUDs running the ATAK Plugin.
