### ISSUE TITLE
[Feature request] more responsive connection status

### ISSUE THREAD

**Issue by prokrypt** [meshtastic/Meshtastic-Android#1006]
On the node selection screen, it would be nice if the status updates once the initial bluetooth connection is established.

I know it's possible because the notification message actually behaves this way:
![Screenshot_20240429-105700-434](https://github.com/meshtastic/Meshtastic-Android/assets/1832555/0399c798-8eda-48be-b969-a984ea1247f3)
... then after around 10 seconds the status message on the node selection screen changes from "Not connected" and starts going through the usual items.

**Comment by andrekir** [comment]
this delay is due to large NodeDBs being transferred during the connection handshake. I can add a node count to the status message so there is better feedback.
