### ISSUE TITLE
Notifications generated to own messages - 2.3.6

### ISSUE THREAD

**Issue by Heppie** [meshtastic/Meshtastic-Android#1009]
Notifications are generated for own messages on sending

![Screenshot_2024-04-30-15-53-27-57_24570ffaa6dee6a40011f001254fdfdb](https://github.com/meshtastic/Meshtastic-Android/assets/1219903/4c013e2c-62da-4c78-a8d4-c9279ae84678)

**Comment by memo-567** [comment]
Same here  ¯\\\_(ツ)_/¯
Possibly since the update to the version Android 2.3.6 alpha?

**Comment by megabyte2010** [comment]
Same here.

**Comment by fti7** [comment]
Same here ;-)

**Comment by Donnie650** [comment]
I get the same result. Unknown user messages everytime I send, same message I sent.

**Comment by andrekir** [comment]
thanks for reporting. this is fixed in 4203b28a45ba941dc41a7fc77c60210455daa869 and will be out in the next release.
