### ISSUE TITLE
Connected Wisblock does not show up on the map 

### ISSUE THREAD

**Issue by Mertszr02** [meshtastic/Meshtastic-Android#1022]
I'm currently connected to a wisblock running 2.3.3

Provide phone location is on

Nodes list shows my location coordinates correctly so it seems the device receives my location without a problem. 

I'll check my home node(T3-S3) when I return home but I think esp devices didn't have an issue with their location on map.
So I will comment an update but I think this a wisblock specific issue.

Also when connecting to a wisblock, nodes list first shows the second node as the connected(first) node. Then quickly shows the correct(BLE connected) node. I don't think these bugs are connected so this may need another issue just wanted to quickly mention it.

Phone meshtastic version: 2.3.6 but I remember seeing these behaviors on previous versions

**Comment by andrekir** [comment]
position is all handled in the firmware
