### ISSUE TITLE
devices don't get to know each other

### ISSUE THREAD

**Issue by cracky22** [meshtastic/Meshtastic-Android#1023]
I currently have 2 repeaters in use and my own handheld device. There are additional repeaters and other handheld devices in the mesh. But my handset only knows one of 2 repeaters. what can I do so that my handset knows the 2nd repeater? The messages still go (traceroute: unknown device) via the repeater (presumably)

**Comment by GUVWAF** [comment]
So it is in `REPEATER` [role](https://meshtastic.org/docs/configuration/radio/device/#roles)? Repeaters won't show up in the node list as the documentation says (unless if was another role before and your device already heard it). 
Set it in `CLIENT` role if you want them in the node list. Clients will also repeat messages.

**Comment by cracky22** [comment]
oh interesting, thanks for the info
