### ISSUE TITLE
Warn users of old firmware version

### ISSUE THREAD

**Issue by wheresalice** [meshtastic/Meshtastic-Android#1031]
We should start showing a warning when users connect to a device with a firmware older than 2.3.2 (I'm open to suggestions on the lowest acceptable version)

This would hopefully encourage more people to upgrade which would help with the overall health of the mesh, and improve the reliability of things like hop count and reporting which messages have come from MQTT

**Comment by Beauxrel** [comment]
Dead link

> This issue has been mentioned on **Meshtastic**. There might be relevant details there:
> 
> https://meshtastic.discourse.group/t/radio-firmware-too-old/13805/2
>
