### ISSUE TITLE
[Feature Request]: Clear display of IQA.

### ISSUE THREAD

**Issue by memo-567** [meshtastic/Meshtastic-Android#1042]
It would be nice if there was also an understandable display of the IQA for the Android app.
Currently, the value is displayed in `MΩ` only.

This is already available for the iPhone app: https://github.com/meshtastic/Meshtastic-Apple/commit/52dd086e09b7b7e6d1e5e693e90e6db38fe98501

At the moment it looks like:

![20240515-1030](https://github.com/meshtastic/Meshtastic-Android/assets/58190287/c848b981-d4f6-430f-9b02-78990fe5306f)

**Comment by grenius** [comment]
That's power telemetry isn't it? Though i agree a weather telemetry page like iOS would be nice.

**Comment by memo-567** [comment]
> That's power telemetry isn't it? 

This value the BME680 sends as IAQ (Indoor Air Quality) https://en.wikipedia.org/wiki/Indoor_air_quality

**Comment by grenius** [comment]
bme680 only has pressure/temp/humidity.

**Comment by memo-567** [comment]
Nope: https://www.bosch-sensortec.com/products/environmental-sensors/gas-sensors/bme680/

**Comment by grenius** [comment]
Oh my bad. Must have been thinking of the 280. Either way i'm onboard with what you're asking.

**Comment by grenius** [comment]
FYI:

MΩ
A unit of resistance in electricity that is equal to one million ohms, also known as a meg

**Comment by memo-567** [comment]
Thanks for the tip, but I'm very familiar with the basics of electrical engineering 😉

**Comment by andrekir** [comment]
IAQ values were added in 2.3.12
