### ISSUE TITLE
When I clear the node DB my fixed position values are reset to 0

### ISSUE THREAD

**Issue by dougjeff** [meshtastic/Meshtastic-Android#1044]
For my home node I use fixed position instead of having a GPS that draws power.
When I set values for the lat, long & alt they appear correctly.
When I do Radio Configuration>Node DB reset and send it my lat, long & alt are reset to 0.

Running Heltec V3 fw 2.3.3
Android app v 2.3.7

I would not expect fixed positions to get reset like this. Or is this the intended behaviour?

Thanks
Doug

**Comment by prokrypt** [comment]
It is the expected behavior for those of us in the know, but I guess it can be considered a bug because everyone else doesn't expect it...
Perhaps a change can be made in the firmware to keep the position when resetting nodedb.

**Comment by caveman99** [comment]
PLease update your device firmware. There was a recent change to not clear node 0 (my own record) when resetting nodedb.

**Comment by caveman99** [comment]
Jzst to amend: it keeps the own node in DB but explicitly resets its position data. So disregard my previous comment, this is intended behaviour.

**Comment by caveman99** [comment]
https://github.com/meshtastic/firmware/pull/3451

**Comment by thebentern** [comment]
Yes this is working as designed.
