### ISSUE TITLE
Bluetooth not reconnecting when coming back within range

### ISSUE THREAD

**Issue by Bryang0syr** [meshtastic/Meshtastic-Android#1046]
Can't be certain but a few days ago when returning instead of reconnecting I now have to re-pair the phone and node each time entering the fixed pin. Not sure when Android 2.3.8 was pushed out but started to notice the problem a few days ago whereas before the reconnection was automatic, running 2.3.6 firmware on Heltec V3

**Comment by todd-herbert** [comment]
Are you still using the same firmware on your node? The only thing that changed was the app version?

**Comment by pomazanbohdan** [comment]
Personally, I just started using it Application version 2.3.10

**Comment by andrekir** [comment]
losing pairing is not an app issue

**Comment by todd-herbert** [comment]
Just to follow up on https://github.com/meshtastic/Meshtastic-Android/issues/1057#issuecomment-2134553637, I haven't noticed it again since then. Probably something had just gone weird on my end for a bit.
