### ISSUE TITLE
Failed Traceroute

### ISSUE THREAD

**Issue by Emmpunkt** [meshtastic/Meshtastic-Android#1047]
Hello,
Feature Request:
Can you add a pop up window (like the result of the traceroute) if traceroute fails?
I use traceroute to check my connection. I don´t want to send a lot of "Test-Test" out and annoy people ;) (difficult terrain)
But i don´t know "when" a traceroute fails. How long does the traceroute command run, till it fails? There is just nothing to see.
Regards Michael

**Comment by prokrypt** [comment]
There is no way to know when a traceroute fails as it can take several minutes for it to return.

**Comment by prokrypt** [comment]
You can start as many as you want, but keep in mind that it does use quite a bit of airtime on its way back to you so there's a higher chance of collisions. Better to wait a while in between each trace.

**Comment by Emmpunkt** [comment]
OK, thank you.
I think you can close this issue.
Michael
