### ISSUE TITLE
feature request: traceroute as selectable text

### ISSUE THREAD

**Issue by GiuStel** [meshtastic/Meshtastic-Android#1049]
Hi,
I often find myself taking screenshots of traceroutes to share with friends over the chats.
It would it be nice if the traceroute would be selectable as text (long pressing a selection, or even better trough a "copy" button) instead.

Thanks a lot!

Giul

**Comment by Nestpebble** [comment]
To add to this, I'd like to see it in the chat history of the DMs with a node. That way I could see its history as I move about...
