### ISSUE TITLE
The application does not reconnect to the device after losing connection

### ISSUE THREAD

**Issue by pomazanbohdan** [meshtastic/Meshtastic-Android#1057]
I am currently using Helteс v3 stationary, at home from a power bank. Connect via Bluetooth. 
When I leave home and return, the application does not connect to the device on its own. 
You have to click Absent and select again.

**Comment by todd-herbert** [comment]
I feel like I have noticed this too, but I haven't tried waiting to see if it does reconnect eventually. I'll give that a go in a few minutes.

I think this might be the same as: https://github.com/meshtastic/Meshtastic-Android/issues/1046

**Comment by pomazanbohdan** [comment]
Dublica

**Comment by Ccz119** [comment]
Also here.
