### ISSUE TITLE
[Bug] rangetest.csv gives an empty file

### ISSUE THREAD

**Issue by djoris** [meshtastic/Meshtastic-Android#1058]
Environment: Meshtastic Android 2.3.10 (alpha). 
The issue is resolved by removing application data.

STR:
1. be connected in Android to a node, for a few minutes
2. Choose "Export rangetest.csv"
3. Choose any filename

Shown behaviour:
The exported file is, seemingly random, either completely empty or contains only a header row.

Expected behaviour:
A file containing all messages that are in the debug log (max 500), or perhaps more.

Work-around:
Removing application data from Android. Sadly I didn't think of trying 'debug pannel' -> 'clear'.
Restarting the app did not resolve the issue.

I believe this issue was already present in 2.3.9 and perhaps earlier versions.

**Comment by andrekir** [comment]
the file will show 0 bytes while it's being generated. it can take a while depending on the database size, just give it some time.
