### ISSUE TITLE
No Voltage by USB-Supply

### ISSUE THREAD

**Issue by karamo** [meshtastic/Meshtastic-Android#1068]
When I supply my **T-Beam v1.1** by **USB**, there is no valid Voltage in the APP:
Only **empty Batt-Symbol ! 0% 0,00V**

FW: 2.3.11
APP: 2.3.10
Android 8.0.0

**Comment by prokrypt** [comment]
that is normal. t-beam measures battery voltage.

**Comment by karamo** [comment]
On one screen on the T-Beam there is an USB-Symbol and on an other screen "USB".
So it could be able that the APP could it also display "USB".
What ist the Problem?

**Comment by andrekir** [comment]
clients just consume data coming from the radios, any change would have to go in the firmware
