### ISSUE TITLE
HopLimit could be set >7

### ISSUE THREAD

**Issue by karamo** [meshtastic/Meshtastic-Android#1070]
In the APP HopLimit could be set >7

APP 2.3.11

**Comment by garthvh** [comment]
The firmware will set it to 3

**Comment by karamo** [comment]
yes, but it would be shown wrong.

**Comment by prokrypt** [comment]
And it would be fine because whoever sets more than 7 hops obviously doesn't know what they're doing. Better to ensure mesh integrity than to guide a user to make bad decisions.

**Comment by Ztrby** [comment]
Maybe there should be warnings if someone try to set it over 5 . It maybe be ok in a small mesh. But it may break a big mesh.
