### ISSUE TITLE
Hops away not always shown

### ISSUE THREAD

**Issue by Zappelphilipp** [meshtastic/Meshtastic-Android#1072]
I am running the newest release (2.7.3 as well as 2.7.11) and the app shows for some nodes "Hops away" but for some other it doesn't even though i for sure know that these particualr node is one hop away. It even is obvious in such a way because it shows as "RSSI and SNR the exact same values as the node i know is node in between.

**Comment by caveman99** [comment]
we have 2.7.x now? ;-) no really, this was introduced quite recently and those other nodes have old firmware.
