### ISSUE TITLE
Position icons Android App

### ISSUE THREAD

**Issue by M7OCM** [meshtastic/Meshtastic-Android#1074]
Just an idea got 2 fixed nodes at home and others with GPS for mobile use. Nodes that don't require GPS (fixed position) render the satellite icon null.

Just wondering if a generic house icon could replace the satellite icon/number when fixed location is used and a cell phone icon for when sharing the phones GPS location?

Thanks 73

**Comment by garthvh** [comment]
The fixed position and phone location details are not sent over the mesh, you only know these details for your node.
