### ISSUE TITLE
ISSUE - G2 Station and Android conflict

### ISSUE THREAD

**Issue by alexn023** [meshtastic/Meshtastic-Android#1076]
I have a G2 Station running Ver 2..4.6.7 and Samsung Android phone S21FE. My node says I am connected to 12/13 available nodes but my phone says I am only connected to my own node. Any advice would be gratefully received.

**Comment by andrekir** [comment]
if you have questions please post at https://meshtastic.discourse.group or join our Discord https://discord.gg/TYHeJpPc
