### ISSUE TITLE
Overlapping ModuleConfig messages in the Debug panel

### ISSUE THREAD

**Issue by mgoljak** [meshtastic/Meshtastic-Android#1081]
As you can see in the attachment - some ModuleConfig messages in the Debug panel are overlapping. Perhaps the date could be positioned in the lower right corner, or in the upper left corner, preceding the debug message.

<img src="https://github.com/meshtastic/Meshtastic-Android/assets/5209614/94938d86-1501-43b2-b6f7-520dbfef2c68" width="500">

**Comment by andrekir** [comment]
fixed in https://github.com/meshtastic/Meshtastic-Android/commit/a543bcbfcd3db29bc67f4764d37ef957714f11bd
