### ISSUE TITLE
Feature Request: Use GeoTiff as map layers

### ISSUE THREAD

**Issue by bagmanden** [meshtastic/Meshtastic-Android#1082]
Use lokal GeoTiff files as map layers somthing like you can do in Atak.

It could be something about selecting browses and then choosing the folder the files are in.

**Comment by andrekir** [comment]
Android 10 added file access restrictions that made it really difficult to access files in local storage without using some really nasty hacks.

so closing this for now, but we would definitely accept this as a contribution. If anyone is interested, check out the details here: https://github.com/orgs/meshtastic/projects/8?pane=issue&itemId=12006922
