### ISSUE TITLE
Feature Request:  Resistance or IQA display by BME680

### ISSUE THREAD

**Issue by memo-567** [meshtastic/Meshtastic-Android#1095]
After updating to Meshtastic Android 2.3.12 alpha, both the resistance value and the IAQ are displayed.

If both can be displayed, can this possibly be limited to the IAQ?

![20240613-1410](https://github.com/meshtastic/Meshtastic-Android/assets/58190287/e846efd6-d52e-46fc-a2b8-a4a4fd8c2815)

**Comment by garthvh** [comment]
This is a good point resistance means nothing to anyone anyways, only the IAQ is useful to humans

**Comment by Donnie650** [comment]
Thats not a true statement, some of us enjoy having All the data that a sensor can output. Maybe allow a switch to turn it on? I'm a numbers person and enjoy all the data.  Please fine a way for both to enjoy output.

**Comment by garthvh** [comment]
> Thats not a true statement, some of us enjoy having All the data that a sensor can output. Maybe allow a switch to turn it on? I'm a numbers person and enjoy all the data. Please fine a way for both to enjoy output.

It is, the value needs additional processing to be meaningful.

**Comment by b8b8** [comment]
Can the text be colour coded too, to the same as Garth's iOS app?

**Comment by garthvh** [comment]
> Can the text be colour coded too, to the same as Garth's iOS app? edit: or maybe a little colour coded dot next to it

Most of this is not in the iOS app yet, but here are some controls using the IAQ scale.

https://github.com/meshtastic/design/issues/18

**Comment by garthvh** [comment]
> What I mean is its not true that people have no use for it. I do, and I'm sure others would like all the data a sensor can provide. Just an opinion.

You can't interpret the value without additional processing, like raw gps coordinates no one is doing this calculation in their head and it does not need to be displayed to humans.

**Comment by Donnie650** [comment]
Will it still be part of the data sent out and just ignored by the app? I do proccess all the data I get and would like to be able to continue to do so with the python cli, rewote meshwatch to do all this. Hope it will remain available in the firmware. If not thats ok too. Thanks for your replys.
![20240511_072026](https://github.com/meshtastic/Meshtastic-Android/assets/133519126/f18819b6-479b-4fa9-ad7f-dc76760c790f)

**Comment by andrekir** [comment]
this can be personal preference and if data has no value it really shouldn't be sent over LoRa
