### ISSUE TITLE
Enhancement : If unknown node - show HEX nodeID

### ISSUE THREAD

**Issue by Dorn8010** [meshtastic/Meshtastic-Android#1097]
Instead of showing Unknown Username, show node ID instead.

This would open the way to the next step to write to a certain nodeID with the app or CLI command.
This would allow to address e.g. a known node with a new device.

**Comment by djripcord** [comment]
I agree this would be a great way of showing it. Helps especially when chatting with multiple nodes that you haven't received telemetry for yet. Instead of every node being anonymous, you at least get some information that helps determine who you're talking with.

**Comment by roha-github** [comment]
You could also enter the long name manually for Unknown Nodes.

Example: the NodeID is 1f5a and I find out in the chat that this is Michael, then I could enter the long name "Michael" in the app. As soon as a node info is received, the long name is corrected.
