### ISSUE TITLE
Message notification but no message showing

### ISSUE THREAD

**Issue by Dafeman** [meshtastic/Meshtastic-Android#11]
When I send a message from one phone, on the other phone with the screen off I get a notification saying message received, however when I unlock the phone the message isn't displayed in the message window. Also on the notification screen the serial number of the device the message was received from is shown. Is it possible to show the users name instead? [Screenshot](https://pasteboard.co/J2EiW7C.png)

**Comment by geeksville** [comment]
Oh!  Both of these should be easy to fix.  I'll get to them sometime in the next weekish.  Thanks for the report!
