### ISSUE TITLE
[Feature Request]: Auto-connect to available node

### ISSUE THREAD

**Issue by jayroos** [meshtastic/Meshtastic-Android#1102]
I move between multiple nodes in my cars, at work and at home. I would like to see the app auto connect to whichever node is available at the time. In my mind this would only happen when the the app does not have a connection and not when there is already a node connected. That would avoid needing any logic for "roaming" between nodes.

I can see that this might not be desired behavior in some circumstances so I would recommend an app preference for whether to enable such functionality.

**Comment by andrekir** [comment]
Duplicate of #774
