### ISSUE TITLE
[Feature Request]: Filter node names and map positions

### ISSUE THREAD

**Issue by mattdrum** [meshtastic/Meshtastic-Android#1107]
I would like the abiliity to fitler node names and map position report by age, and by node names.

Age Filter:
If the position report is older than the set filter value it would not be displayed. A value of 0 hours would turn the filter off.

Node Filter:
The filter menu should have a header with selections to view all nodes, block nodes, or view only selected nodes. 
-Each node name would have a checkbox with an X or a checkmark or blank. A placeholder for "New nodes" would also have this option and would defaut the new node to the desired selection. 
-When a node name is X and the "Block Selected" option is selected, then blocked nodes would not be displayed. 
-When the "View Selected" option is checked, nodes wih an check would be visible. When neither the "Block Selected" or "View Selected" option is selected, then all nodes would be displayed.

**Comment by andrekir** [comment]
sounds really complicated. filters added to the nodelist are used in the map view since 2.3.11.
