### ISSUE TITLE
Multiple DM Window/Entries

### ISSUE THREAD

**Issue by fti7** [meshtastic/Meshtastic-Android#1125]
Testing with https://github.com/TheCommsChannel/TC2-BBS-mesh
DM to "ftb1" with "hey"
Instead of the Response in the same Window/Entry, i got a new one.

Seems like the "to" ID is corrupt. Afaik i went to the DM from the Nodes Tab. I cant really reproduce it. But it happens from time to time.
App Cache/Storage Client didnt fixed it

![image](https://github.com/meshtastic/Meshtastic-Android/assets/7014664/a13c4926-db98-4011-9fba-b682c9364bb4)
![image](https://github.com/meshtastic/Meshtastic-Android/assets/7014664/9672bb94-04fb-4256-94d8-d6f233b56812)

**Comment by andrekir** [comment]
different channels. received message came in your primary channel, DM was sent over your channel 1.

**Comment by fti7** [comment]
> different channels. received message came in your primary channel, DM was sent over your channel 1.

thx, ah ok.... that makes sense. So its an TC2-BBS Issue.
Is there any way i can influence with which channel it sends? or is it random? that device and i have both configured (channel 0 +1). Maybe it should also show in the DM Window which channel it uses

**Comment by CommanderCrash** [comment]
This bug still happens and if you have LongFast it will always default it to that instead.
