### ISSUE TITLE
[Bug]: Crash when adding a channel and a channel exists with a blank name

### ISSUE THREAD

**Issue by RichieFrame** [meshtastic/Meshtastic-Android#1135]
In the case where there is an existing channel with the 'default' empty name, verified with the web client, attempting to add an additional channel will fail, the app crashes when the + button is pressed. Changing the name to the actual name of the default, such as LongFast using the web client will allow the app to once again be able to add channels

**Comment by andrekir** [comment]
update https://github.com/meshtastic/Meshtastic-Android/releases/tag/2.3.15
