### ISSUE TITLE
[Feature Request]: Show age of position updates in node list

### ISSUE THREAD

**Issue by RichieFrame** [meshtastic/Meshtastic-Android#1137]
We may hear from a node, which will update its last seen time, but the last position update is probably not the same. Knowing the time we received the last position update is very important for tracking type nodes, the age of the node's position update should be shown on the same line as the satellite lock count.

If the GPS timestamp is transmitted with the position, this should be used to calculate the last position time, as it is the time of actual fix of position, rather than when the packet with the position was sent, and there can be more than a minute of variation between the two.

**Comment by andrekir** [comment]
position details are shown on the map
