### ISSUE TITLE
[Feature Request] Map links behaviour

### ISSUE THREAD

**Issue by kittenarmy** [meshtastic/Meshtastic-Android#1139]
In my area there are not many nodes. I notice I am often looking to see where new nodes are between two apps (the map tab and Google Maps). 

Currently clicking on coords in node list opens Google Maps but it would be nice if there was an option for these links to default open in the map tab. Maybe because the map tab exists I expected it to be default behaviour, but I see why Android handles map links this way.

Alternatively, it would be useful to have an option in the context menu when you click on a node Shortname to "view in map" which opens the map tab on the correct tile at default zoom.

**Comment by RichieFrame** [comment]
It may be helpful to allow copy of the location via context menu:
- Show in map view
- Open in default mapping application
- Copy location to clipboard as LAT/LON
- Copy location to clipboard as MGRS
- etc
