### ISSUE TITLE
[Feature Request]: Ability to filter map view by channel

### ISSUE THREAD

**Issue by RichieFrame** [meshtastic/Meshtastic-Android#1142]
Users may have a channel dedicated to tracker nodes, or may not want to see positions of nodes on the public channels. Adding the ability to filter nodes by which channels their position updates are sent over would be very helpful in reducing clutter and allowing focus on specific nodes.

**Comment by andrekir** [comment]
if you're looking for any specific nodes the map will honor the nodelist name filter, but other than that there is no plan to introduce map specific filters.
