### ISSUE TITLE
Bluetooth issue

### ISSUE THREAD

**Issue by Commander-Crash** [meshtastic/Meshtastic-Android#115]
On android 8.1 It will go into a Bluetooth pair loop will not let me enter the pair key will cut off and ask to pair again and again I have tried this on 3 phones all sky devices but different models same 8.1 android I do not have another phone that this can be tested on It may just be the phones IDK. It would be grate if their is a option to pair automatically without a key entered but I assume this is not possible due to android BT stacks.

Using a ttgo lora32-v1 1.0-US/0.7,11

**Comment by Commander-Crash** [comment]
This issue seems to have been resolved in the 0.9.01 android release.

**Comment by geeksville** [comment]
yay!
