### ISSUE TITLE
Number of connected nodes in app do not match information on node

### ISSUE THREAD

**Issue by Marvin-YYC** [meshtastic/Meshtastic-Android#1154]
The connected nodes shown on the Android app do not match information shown on my nodes.  For example my node shows that I am connected to 40 of 45 nodes (40/45) but the app indicates that I am connected to 1 of 45 nodes online. As well the date/time stamp of when I was connected to the node is incorrect and now normally shows 10 days or 98 days.  Sometimes it even shows my own node hasn't been connected to for 10 days even though I am currently connected to it, or it shows that I am connected to zero nodes.   I'm connecting by Bluetooth, but the issue also occurs while using IP connection.
This issue has been ongoing since the last couple updates since about 2.3.11

**Comment by andrekir** [comment]
indeed, the firmware uses a different time frame to count online nodes (2 hours IIRC).

all data, including time, comes from the radio. very likely your node has bad time. you can confirm by checking your logs. sharing your phone GPS should also clear this.
