### ISSUE TITLE
[Feature Request] Choose Channel/Key for new DM

### ISSUE THREAD

**Issue by fti7** [meshtastic/Meshtastic-Android#1166]
If the other Node is available over multiple Channels (e.g. LongFast and some private one). 
Let User choose with which Channel/Key the "New Direct Message" will be opened

**Comment by garthvh** [comment]
This needs to be managed in the firmware.

**Comment by jp-bennett** [comment]
I agree with the sentiment, but the solution is the PKI support landing in 2.5. DM's will be their own pseudo-channel, rather than piggy-backing on one of the existing channels.
