### ISSUE TITLE
[Feature Request] Filter Node list by time since last contact

### ISSUE THREAD

**Issue by barryhunter** [meshtastic/Meshtastic-Android#1171]
I think it would be really neat/useful to be easily filter the node list to only show nodes with recent contact. 

This could perhaps be powered by the 'search' box, without having to add another button. For example if enter [-10m] will only shows nodes seen in last 10minutes. 

I know can see this information on the list, but always takes a moment to 'mentally' filter the list by checking the time. 

A lot of the time, I'm just testing, and want to see if currently getting contact, not interested (at that moment) in nodes seen yesterday for example. Particularly relevant when mobile. 

Would be nice to be able to 'filter' (not just sort) by some of the others too. But a 'last heard' seems most useful to me, although 'hops away=0' would be nice.

**Comment by Talie5in** [comment]
Isnt this "Sort by Last Heard" which will show the most recent heard packet node's at the top of the list?

**Comment by barryhunter** [comment]
Yes, sorting does make it easier. But you still need to actully look at the times on each node, or at least look down until find where switches. 

ie if only interested in recent contacts, have to look at the result to see if recent, so can 'mentally' filter. And stop looking at more results. 

Or if want to see how many recent contacts there are, can scroll down and see where it goes over and stop. But still have to look at each one. 


Its by no means an 'essential' feature, but would make working with lists easier.

**Comment by fti7** [comment]
https://github.com/meshtastic/Meshtastic-Android/issues/1145
Only show Nodes since "enabling" that Feature would be very nice.
