### ISSUE TITLE
Ack messages are ignored by UI

### ISSUE THREAD

**Issue by jaredcat** [meshtastic/Meshtastic-Android#1182]
App version: `2.4.0` on Android 14
Meshtastic: `t-echo 2.4.1.394e0e1`

Almost all of my messages end up with "ERROR"
but when I look into the debug panel, I can see that at least one of those did receive an ACK with matching ID.

For a long time, this made me think that none of my messages were getting out.

Are messages not updated after a certain time? I think they should be updated if an ack is received at any time. 

If this all working as expected, then I would say this UX is confusing to new users.

![Screenshot_20240805_123359_Meshtastic](https://github.com/user-attachments/assets/44a174c9-8b34-4e09-b189-01c742c158fe)

![Screenshot_20240805_123347_Meshtastic](https://github.com/user-attachments/assets/3e2cc41f-253a-4344-b863-a8a83648f4a6)

**Comment by GUVWAF** [comment]
I believe the UI is correct. This is most likely not an ACK, but a NAK with "Max retransmission reached" error. You'll have to decode the payload to see the error code.

Indeed it has the priority of an ACK, but all routing packets have this.
