### ISSUE TITLE
Be able to connect to a device without updating any change

### ISSUE THREAD

**Issue by lgoix** [meshtastic/Meshtastic-Android#119]
After pairing a device, it could be nice to see the current config and not override it immediatly after.

The issue I am having with many nodes is each time I connect to the next device, it has the same name than the previous one, and I don't remember the old name it has or the network config it has.

**Comment by geeksville** [comment]
oh smart - I agree.  We can nicely test for this case, by using the nodeid of the locally connected radio.  If it changes we shouldn't just slam in settings, but rather ask the user.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/meshtastic-0-9-03-app-issues/1160/4

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/alpha-tester-thread-0-9-06-android-app-ready-for-testing/298/298
