### ISSUE TITLE
[Feature Request] Enable QR code scanning support for sharing WiFi credentials

### ISSUE THREAD

**Issue by scotty6435** [meshtastic/Meshtastic-Android#1192]
Modern mobile operating systems (including Android) have QR code support for sharing the SSID and password of a network. Building this into the android, Android and web apps would reduce barrier to entry.

**Comment by andrekir** [comment]
copy paste is your friend, but fair enough. cool idea.

**Comment by scotty6435** [comment]
True but you can't copy paste the back of a router. And I don't believe android allows you plaintext access to a saved SSID's password. I'd rather not have to use OCR to take a snap and convert that to something usable
