### ISSUE TITLE
[Feature request] Track and maintain unsaved changes to radio configuration

### ISSUE THREAD

**Issue by scotty6435** [meshtastic/Meshtastic-Android#1193]
Whilst setting up my first node today I had an annoying problem. As I was setting it up with my phone and my phone had a picture of my SSID password, as I switched between apps to read the values out, the app would delete on return anything I had previously entered.

I can understand why the app would play safe and pull down a fresh copy of the config when it comes back into the foreground but it would be a lot better if:

 * The UI tracked when a change was made anyway (colour and icon/text status) - this would generally make it clearer what's changing.
 * On refresh anything that had been previously recorded as 'modified' was retained.

**Comment by prokrypt** [comment]
What phone do you have and what are its specs? I suspect your phone is running out of memory (or doing some Weird Things) and unloading the app when you switch to another app.
I have no such issue with my phone, unless I load the camera which then kills everything in the background 🫠

**Comment by scotty6435** [comment]
It's a pixel 7a so not a low spec phone. I was also live switching between two apps, there would be no time for the OS to suspend meshtastic

**Comment by b8b8** [comment]
Interesting. I just tried this on my Pixel 7a and was able to switch between pictures the password box, and any other app.

**Comment by scotty6435** [comment]
I'm not getting it either. I can only think that either it only manifests on a brand new device, via Bluetooth or my phone was somehow under such ram load that it was pushing the app into the background immediately
