### ISSUE TITLE
[Feature request]  Show the hop count on the node pins on the map (like this https://pole1.co.uk/node-plot/ )

### ISSUE THREAD

**Issue by Paul-Pressure** [meshtastic/Meshtastic-Android#1196]
[Feature request]  
Show the  HOP COUNT  on each node pin on the map 
like this  https://pole1.co.uk/node-plot/

**Comment by Paul-Pressure** [comment]
Just to add, I feel having this information will help as all get a better understanding of the real world routing for the good of the mesh :)

**Comment by b8b8** [comment]
how about colour code the info window background. Green for zero hops, lighter green for 1 hop, really light green for 2 hops. orange for 3 hops etc.

**Comment by andrekir** [comment]
the map is simple and for now not really intended for showing complex data or as a network topology tool. also keep in mind hops aren't static, especially in larger meshes, they can change a lot. for a more in-depth network visualization tool have a look at https://github.com/meshtastic/network-management-client

**Comment by Paul-Pressure** [comment]
Hi @andrekir  no problem understand
