### ISSUE TITLE
Add option of 13 to channel position precision 

### ISSUE THREAD

**Issue by thebentern** [meshtastic/Meshtastic-Android#1197]
As a part of the discussion for https://github.com/meshtastic/firmware/pull/4467, @garthvh brought up a good point that the default value of 13 in the iOS app has a legal basis. So I'd like to set that as the default value in the firmware and have that as an option in all of the clients

**Comment by b8b8** [comment]
Can we get the actual diameter (or radius) in m/km next to each setting as well?

**Comment by andrekir** [comment]
look like this will keep coming up until we have the full range, so lets do that. the default for MQTT map report is 14 and also not covered. tracking this in #1186
