### ISSUE TITLE
Position precision slider in mqtt and channel settings jumps around 

### ISSUE THREAD

**Issue by valzzu** [meshtastic/Meshtastic-Android#1213]
### Contact Details

valzzu_

### What happened?

When setting position precision the slider jumps back to 14.5 miles see attached video.

https://github.com/user-attachments/assets/b11958cc-a22b-45c1-9b66-7bcc2c1c77d1

### App Version

2.4.3

### Phone

Samsung galaxy A55

### Device

Wisblock 

### Firmware

2.4.0.46d7b82

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
update. this was fixed in [2.4.4](https://github.com/meshtastic/Meshtastic-Android/releases/tag/2.4.4).
