### ISSUE TITLE
Position precision slider in metric

### ISSUE THREAD

**Issue by valzzu** [meshtastic/Meshtastic-Android#1214]
### Tell us your idea.

Would be nice if the position precision slider was in metric for us what use it :)

In mqtt and channel settings 

![Screenshot_20240828_221254_Meshtastic](https://github.com/user-attachments/assets/424b2380-654a-4ea4-bc2b-366a987b4004)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by b8b8** [comment]
my suggestion that i posted on discord at the time was to just display both units. this is only shown when actually making the change and there seems to be sufficient room.

**Comment by andrekir** [comment]
go to **Android Settings > Language** and change your Country to something other than ... (United States) or ... (United Kingdom)

**Comment by mkgin** [comment]
> my suggestion that i posted on discord at the time was to just display both units. this is only shown when actually making the change and there seems to be sufficient room.

Both units would just be confusing... likely undesired by most... off to the shop to by some two by fours... which will surely be less than 5cm x 10cm.

**Comment by b8b8** [comment]
Andre is right. I had the same issue. For some reason EVERYTHING on my phone was set to metric/Canadian except somehow language defaulted to USA. It works now perfectly. Idk if it was random android update.

**Comment by valzzu** [comment]
ye now i got in metric :)
