### ISSUE TITLE
Wrong role displayed on device list (client instead of Router)

### ISSUE THREAD

**Issue by Mertszr02** [meshtastic/Meshtastic-Android#1218]
### Contact Details

[mertszrdev@gmail.com](mailto:mertszrdev@gmail.com)

### What happened?

Device list shows shows all routers as clients, 
I have 2 routers and 1 old router_client.
One of the routers (R2) is near me so its more up to date v2.4.1 
I don't remember the versions of the other two.
List shows my own client_mute device correctly.

![Screenshot_2024-08-30-13-17-00-112_com geeksville mesh~2](https://github.com/user-attachments/assets/9a511c5b-e15a-410d-a09c-b5d42d819d24)
![Screenshot_2024-08-30-13-25-55-323_com geeksville mesh~2](https://github.com/user-attachments/assets/8fa15746-90a1-4422-9798-217025ca6620)
![Screenshot_2024-08-30-13-22-01-792_com geeksville mesh~2](https://github.com/user-attachments/assets/65040419-79a4-427a-83df-ddf5404eaee1)

### App Version

2.4.4

### Phone

Xiaomi 13T

### Device

Rak4631

### Firmware

2.4.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mertszr02** [comment]
Ok this is interesting. I have changed nothing yet the nodes list now shows the correct roles.
My node was in my room disconnected from the phone, I came back and checked the list.

Could it be:
Role of the remote nodes were unknown at first and the default value is client so it shows client?


![Screenshot_2024-08-30-18-13-21-378_com.geeksville.mesh~2.jpg](https://github.com/user-attachments/assets/502dda20-45b2-4322-87e1-c68330e00844)

**Comment by jamesarich** [comment]
> Role of the remote nodes were unknown at first and the default value is client so it shows client?

Yep, this is indeed the case - the default (unset) value of 0 equates to `CLIENT` role.

https://github.com/meshtastic/Meshtastic-Android/blob/cb2ea2804a19caec29f0b8322cf26872e21904a5/app/src/main/java/com/geeksville/mesh/NodeInfo.kt#L32-L33

**Comment by Mertszr02** [comment]
Thanks, this feels kinda misleading. Not a big deal but I think it can have a default (eg: unknown) value

**Comment by jamesarich** [comment]
#1219 adds defaults for the device values in that row when unknown
