### ISSUE TITLE
[Feature Request]: Add the ability to filter out nodes not seen in X minutes

### ISSUE THREAD

**Issue by vext01** [meshtastic/Meshtastic-Android#1221]
### Contact Details

vext01 on discord

### Tell us your idea.

At present the node list shows all the nodes ever seen for all time.

Often it's useful to see only nodes that are likely to be "online right now".  It would therefore be useful to add a "show only nodes seen in the last X minutes" feature, where X is configurable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
Duplicate of #1171
