### ISSUE TITLE
Disable Android service after disconnecting from device.

### ISSUE THREAD

**Issue by drewsed** [meshtastic/Meshtastic-Android#123]
Once connected to a Meshtastic device via Bluetooth, a notification appears on the phone, that it is connected and it shows how many devices are online plus the last message. 

When disconnecting on the right most tab page switching to "None (disable)” a notification still appears shows up (disconnected).

After closing the app via recent apps, this notification still shows up. Same thing with exiting via back button. 

Greetings,
Drew

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/how-do-i-stop-the-android-app-properly/941/7
