### ISSUE TITLE
[Bug]:  On  Node list in Dark Mode, division between nodes (Minor)

### ISSUE THREAD

**Issue by Paul-Pressure** [meshtastic/Meshtastic-Android#1246]
### Contact Details

djp_pressure@hotmail.com

### What happened?

  On the node list in Dark mode with show details ticked the dividing horizontal lines are misleading not between nodes. Suggest either align with the background shading or have one or the other. 
![Screenshot_20240914_212236_Meshtastic](https://github.com/user-attachments/assets/986bc2c5-442b-4dea-a0ff-5bca6d63748b)

### App Version

2.5

### Phone

Samsung Galaxy S24

### Device

Heltec V3

### Firmware

2.4.0  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by b8b8** [comment]
A slightly higher contrast between the background and the card would also be helpful.
