### ISSUE TITLE
[Feature Request]: Remote admin using PKC

### ISSUE THREAD

**Issue by djholt** [meshtastic/Meshtastic-Android#1247]
### Tell us your idea.

I've now removed the admin channel in my network, and I'm curious if we currently have PKC remote admin on the roadmap for Android. Thanks for the all of the incredible work!

I imagine this would use the same remote config UI and utilize keys when the admin channel is not enabled for a node.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by b8b8** [comment]
https://github.com/meshtastic/Meshtastic-Android/releases/tag/2.4.8

Already in 2.4.8 App

**Comment by djholt** [comment]
Oh! I looked and came up empty. Thanks!!
