### ISSUE TITLE
QR sharing URL format potentially leaks channel keys to remote server

### ISSUE THREAD

**Issue by gkelly** [meshtastic/Meshtastic-Android#126]
Right now the URL format for the QR-shared channel details looks like this: `https://www.meshtastic.org/c/CBciENTxuzogKQdZ8Lz_q89Oab8qB0RlZmF1bHQ=`

Which encodes the channel name, parameters, and key into the URL path. When shared, there's a non-zero chance that this URL gets fetched. Someone taps the link (and admittedly gets a 404) but the URL _path_ is being sent to `meshtastic.org`. Anyone with access to the hosting logs can potentially see the `GET /c/CBciENTxuzogKQdZ8Lz_q89Oab8qB0RlZmF1bHQ=` request and take the channel configuration including the key.

I believe there's a fairly easy solution here: placing the channel configuration in the URL fragment instead of the path. The URL fragment identifier is _not_ sent to the server when browsing to the URL. So even if the URL is clicked/tapped/cached by a browser fetch the channel options never get sent to a remote machine.

**Comment by geeksville** [comment]
great find!  I totally agree.  Though I guess the risk is limited slightly if the person has the meshtastic app already installed, in that case the URL should never get sent off device.

But your fix also sounds great.  I'll add a comment there.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/alpha-tester-thread-0-9-2-android-app-ready-for-testing/298/237

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/android-app-new-releases/78/62
