### ISSUE TITLE
[Bug]: Delete Messages Missing Android 2.4.12

### ISSUE THREAD

**Issue by skykingisepic** [meshtastic/Meshtastic-Android#1289]
### What happened?

Delete Messages option missing

### App Version

2.4.12

### Phone

Pixel 6 Android 14

### Device

n/a

### Firmware

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
update your app, this is fixed in the latest alpha
