### ISSUE TITLE
[Bug]: Connected node saying last seen 99 days | Seen nodes last seen 99 days 

### ISSUE THREAD

**Issue by Properrumble** [meshtastic/Meshtastic-Android#1291]
### What happened?

This issue has now been seen across **three individual nodes**,  **two different mobile devices** (A Galaxy S24 Ultra & Galaxy Tab S6) and across at least **two different versions of the V3 firmware**, so I can only assume this is an app software issue, not a hardware/firmware one with the individual boards (all Heltec V3s).

### **Symptoms**

- The connected radio/node keeps displaying as last seen 99 days ago, despite the green ticked cloud icon in the app indicating that it is presently connected. This sometimes fluctuates periodically, with the unit sometimes showing as seen 'now', but with the issue listed below also occurring. When first starting up the unit, it will initially shown last seen as 'now', but then change to 99 days.

- Seen nodes don't seem to be retained in terms of when last seen. Similar to the connected node linked to the software, they appear as last seen 99 days ago. Sometimes this fluctuates with them being seen on and off again.

### Steps taken so far

1) Updated all three nodes to the latest stable firmware from the Meshtastic flasher website.

2) Completely reset the nodes with a full erasure via the Meshtastic flasher website. (For some reason, factory reset via the app wasn't working, which may also be a bug worth reporting.)

3) Connected to two different mobile devices to remove the possibility/variable of the phone being the issue.

### Screenshots

![1](https://github.com/user-attachments/assets/7eac6afd-e98c-46d9-bdbb-d6f18bd01ed3)

![2](https://github.com/user-attachments/assets/9307dd21-d949-43a5-8eb5-6ba232ca62a0)

![3](https://github.com/user-attachments/assets/9c33953a-8d6f-4a00-a687-abd20b136a2e)

### Comments

As it stands, my entire mesh network is totally unusable due to this issue. Without the ability to see what nodes I'm connecting to, I have no bearing on my effective range, cannot estimate mesh infrastructure nearby me, etc.

### App Version

2.4.4

### Phone

Samsung S24 Ultra

### Device

Heltec V3

### Firmware

2.4.2.5b45303 Beta

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
your node has bad time. nodes without GPS/NTP use position broadcasts as a time source. 2.5.4 was just promoted to beta today, give it a try.

if you're on a public mesh, move public or MQTT channels out of your primary channel.

you can use Android GPS to fix the node's time. if you don't want to broadcast your location, set a fixed position first.
