### ISSUE TITLE
[Bug]: metrics not chronological

### ISSUE THREAD

**Issue by Bergstern** [meshtastic/Meshtastic-Android#1296]
### Contact Details

andre.kammerlander@gmail.com

### What happened?

At the Metrics page the data is sometimes not chronological. Data from the morning shows up after data at the evening so the graph is wrong.

### App Version

2.5.0

### Phone

One Nord 3 Plus

### Device

rak4631

### Firmware

2.5.5.e182ae7
![Screenshot_2024-10-09-18-28-59-18_24570ffaa6dee6a40011f001254fdfdb](https://github.com/user-attachments/assets/4349da18-c4e0-4c70-b99f-10415baf63c7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
fixed in https://github.com/meshtastic/Meshtastic-Android/commit/a3b4b70db9137bf46e858558fb676a86661b8bb6
