### ISSUE TITLE
[Bug]: 2.5.1 - Sort by Hop - Sorts Unknown before 0,1,2,3 etc Hops

### ISSUE THREAD

**Issue by Talie5in** [meshtastic/Meshtastic-Android#1301]
### Contact Details

@Talie5in

### What happened?

When sorting by "Hops away", the new "Unknown" sorting is putting the "Unknowns" before 0 Hops devices - These would make more sense sorted between Max Hops and "Offline" devices (or devices not seen for a few hours).

![Screenshot_20241011_132311_Meshtastic](https://github.com/user-attachments/assets/e95cc277-0d5e-4d4c-9f76-f6ebb5003ecb)

### App Version

2.5.1

### Phone

Android

### Device

Any

### Firmware

Tested against 2.5.4, 2.5.5, 2.5.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jamesarich** [comment]
oops - fix coming
