### ISSUE TITLE
[Bug]: Nearly all nodes show as "hops away: unknown" 

### ISSUE THREAD

**Issue by noon92** [meshtastic/Meshtastic-Android#1304]
### What happened?

Since most recent update of app, nearly all nodes in the node list show as unknown hops away. In the debug log, the hopstart and hoplimit values show correctly, as shown in the debug log I've attached, but in the node list that same node will show hops away as unknown. 

Interestingly, it seems that nodes that are zero hops away are displayed properly. Looks like every other node shows as unknown. 

App Version 2.5.1
Firmware: 2.3.13

### App Version

2.5.1

### Phone

Pixel 8

### Device

4631

### Firmware

2.3.13

### Relevant log output

```shell
Example packet from debug log:

from: sendingnode (!nodeid)
to: destnode (!ffffffff)
channel: 2
decoded {
  portnum: TELEMETRY_APP
  payload: "abunchoftelemetry"
}
id: 1655078988
rx_time: 1728667827
rx_snr: 8.0
hop_limit: 2
rx_rssi: -78
hop_start: 7
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ianmcorvidae** [comment]
I probably didn't catch this in my review, my bad. We've got:

```
                // Generate our own hopsAway, comparing hopStart to hopLimit.
                it.hopsAway = if (packet.hopStart == 0 || packet.hopLimit < packet.hopStart) {
                    -1
                } else {
                    packet.hopStart - packet.hopLimit
                }
```

and in the second line there, the inequality should be the opposite direction (it's an invalid hops away if the hop limit (remaining hops) is higher than the hop start, not the other way around (which is normal)

**Comment by ianmcorvidae** [comment]
@jamesarich sorry to not catch this in #1295 -- missed that the inequality needed flipping since the condition had otherwise been inverted

**Comment by jamesarich** [comment]
fix coming, good catch.
