### ISSUE TITLE
[Feature Request]: add variables in "quick chat" messages.  

### ISSUE THREAD

**Issue by SZemanek** [meshtastic/Meshtastic-Android#1311]
### Tell us your idea.

I think the "quick chat" feature would be more useful it supported variables in the quick chat message.   

Some ideas for built-in variables could be:
- Current phone GPS location
- GPS altitude, speed, or direction. 
- Phones local date/time.  (since meshtastic messages aren't timestamped)
- A list of nodes that have recently been heard from directly. 
- Meshtastic device firmware version.  
- Device battery level, charging status, etc. 
- Android app version number. 
- Signal strength info from a certain node.  
- Distance / direction to/from a certain location. 
- Meshtastic device uptime 
- Cell phone network signal strength, internet latency, etc.  (could be useful in a disaster) 
- The ability to read contents of a text file on the android device file system.   (this might be useful if a script is fetching data from the internet or something) 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
adding complex quick chat options is not currently planned
