### ISSUE TITLE
[Feature Request]: Update paired nodes list in app to reflect changed node name --> [short name]_MAC

### ISSUE THREAD

**Issue by mtsdawson** [meshtastic/Meshtastic-Android#1315]
### Contact Details

skelzer

### Tell us your idea.

I'd like the app to... update the list of paired and available nodes to display the new shortname_mac name after changing this in the User Config panel.  Currently, the original "Meshtastic_mac" name persists.  This forces the user to unpair, then repair the node to update the list to the changed name, which can be tedious when doing a mass FW upgrade with wipe of 10-20 nodes.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mtsdawson** [comment]
Although this doesn't happen automatically, I did find a fix:

- close the android app.
- visit BT paired devices in phone's settings, wait for a few seconds, then old "Meshtastic_mac" name refreshed to new name.
- open Meshatastic app, wait a few seconds, then old "Meshtastic_mac" name also updated to new name.

I have to imagine there's no way to do this automatically, so I'm closing the issue.

**Comment by andrekir** [comment]
Bluetooth names are provided by the Android system. How and when they are updated varies depending on the brand and model. There's not much we can do from the app side to change that.
