### ISSUE TITLE
Publish APK on F-Droid

### ISSUE THREAD

**Issue by Alixpat** [meshtastic/Meshtastic-Android#132]

**Comment by geeksville** [comment]
alas - fdroid doesn't allow analytics (even if it has opt-out).  And IMO analytics is too useful a tool for tracking down bugs.   If someone wanted to add ACRA (and host the server) then maybe it would be possible. https://github.com/meshtastic/Meshtastic-Android/issues/6#issuecomment-599169031

For now though closing. alas. ;-)
