### ISSUE TITLE
[Bug]: Using android ver 2.5.2, remote node metrics display 12/31/69 date, time is off also

### ISSUE THREAD

**Issue by RightHandMan1** [meshtastic/Meshtastic-Android#1328]
### Contact Details

@RightHandMan

### What happened?

After loading FW 2.5.5 on 3 nodes, heltec V3's, starting checking metrics feature. Date and time are current on RHM1 connected thru wifi to tablet with 2.5.1. Checking RHM2 and 3 metrics, all metrics seems working except, both dates are from 12/31/69 and times are off +-45min. I have reset both 2 and 3 with no change. All else remotely seems to work. remote admin, and texts to/from each other are fine..

### App Version

2.5.2

### Phone

Samsung tablet A7, android 14

### Device

heltec V3

### Firmware

2.5.5

### Relevant log output

```shell
Oct.17 2024 on tablet and RHM1, RHM2 and RHM3 shows 12/31/69 6:10:45 PM
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
all data comes from the node. see https://github.com/meshtastic/Meshtastic-Android/issues/1291#issuecomment-2395345761
