### ISSUE TITLE
[Feature Request]: mark as read

### ISSUE THREAD

**Issue by cracky22** [meshtastic/Meshtastic-Android#1333]
### Contact Details

martinblieninger2208@gmail.com

### Tell us your idea.

Option that you can mark notifications as read by clicking in the notification center and thus the person opposite gets the read symbol

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
this is not possible without firmware support.

**Comment by caveman99** [comment]
@andrekir can't you do something similar with tapbacks?

**Comment by cracky22** [comment]
> this is not possible without firmware support.

Is it not possible to add this anyway or to discuss it with the firmware team?

**Comment by cracky22** [comment]
> this is not possible without firmware support.

Is it not possible to add this anyway or to discuss it with the firmware team?

**Comment by andrekir** [comment]
@caveman99 a tapback sends a message reply. For a 'read receipt,' something different would need to be implemented.

**Comment by caveman99** [comment]
Yes, I thought a special value for the tapback could be used. It requires a message back anyway, and these were already there.
