### ISSUE TITLE
[Feature Request]: settings for notification

### ISSUE THREAD

**Issue by cracky22** [meshtastic/Meshtastic-Android#1334]
### Contact Details

martinblieninger2208@gmail.com

### Tell us your idea.

Setting option so that you can choose which pop-ups you get (just notifications or whether connected and how many users are online

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
You can already do this through Android’s **Settings > Apps > Meshtastic > Notifications**. There are currently three separate notification channels: service, message, and new node notifications. Choose which ones you want to see or customize how they appear.

Samsung hides that option in the Advanced settings, search for something like "Manage notification categories for each app".

**Comment by hb9eue** [comment]
Thank you for telling how to disable, the 'new node' notification, which was driving me crazy!
