### ISSUE TITLE
GPS History in Android App 

### ISSUE THREAD

**Issue by cracky22** [meshtastic/Meshtastic-Android#1336]
### Contact Details

martinblieninger2208@gmail.com

### Tell us your idea.

I'd like the app to have a GPS History in Android App like already in iOS 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
Duplicate of #550

**Comment by cracky22** [comment]
How long does it take until the feature arrives?
