### ISSUE TITLE
Exclude node text with "-"

### ISSUE THREAD

**Issue by 369Martin369** [meshtastic/Meshtastic-Android#1342]
### Tell us your idea.

I'd like to exclude all nodes with the popular "noreply" in their name, by simply adding "-" to the word "noreply" in the user search field
![Screenshot_20241023_212602_Meshtastic](https://github.com/user-attachments/assets/4679a1e4-8c90-47c4-b250-938907c2a585)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
adding complex filtering options is not currently planned
