### ISSUE TITLE
[Bug]: local name wrong and no cloud icon on sent messages

### ISSUE THREAD

**Issue by valzzu** [meshtastic/Meshtastic-Android#1349]
### Contact Details

valzzu_

### What happened?

local name shows as _ocal_
and messages I send no longer has the cloud icon showing the status of the message
![image0](https://github.com/user-attachments/assets/7e269625-9e13-4e91-a93b-f27f3c0b3db8)

### App Version

2.5.4

### Phone

galaxy A55

### Device

T1000-E

### Firmware

2.5.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jamesarich** [comment]
looks like this got introduced in 5cf9741b139b74ba5368190d03585007fa0e0cdf

**Comment by Paul-Pressure** [comment]
Have this issue too  (galaxy S23 ultra)  , thanks for flagging :)
