### ISSUE TITLE
[Bug]: No further translations possible

### ISSUE THREAD

**Issue by brebtatv** [meshtastic/Meshtastic-Android#1352]
### What happened?

No further translations possible

Translations - the option to translate some texts is missing. 100% of the texts to be translated have already been translated into the Czech language. However, many of them cannot be translated because they are missing from the translation tool.
Namely:
- in the list of last seen nodes, the text "now" is not offered for translation
- after clicking on the short name: "Request user info", More details"
- the entire "More details" tab (screen).
![Screenshot_20241026_151740_Meshtastic](https://github.com/user-attachments/assets/f4a05e6d-b12a-4831-afb1-eedc413bb036)

### App Version

2.5.5

### Phone

Samsung Galaxy S10

### Device

RAK6431

### Firmware

2.5.7.f77c87d

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
Thanks for your contributions!

New source strings are added to Crowdin when they are ready. It's a manual process and takes some time. Also not all strings are sent for translation.
