### ISSUE TITLE
Test button (ext. Notification)

### ISSUE THREAD

**Issue by F13crack** [meshtastic/Meshtastic-Android#1357]
### Contact Details

F13-1nfo@outlook.com

### Tell us your idea.

I'd like the app to have a button in the external notification settings, so you can test your settings without needing another device to send you a message.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cracky22** [comment]
nice idea. is it possible to have a seperate button which triggers a single "beep" to find the node -> "findMy function..."

**Comment by andrekir** [comment]
this would have to be implemented in the firmware. there is no way clients can trigger external notifications coming from the radio.

**Comment by cracky22** [comment]
> this would have to be implemented in the firmware. there is no way clients can trigger external notifications coming from the radio.

that means what do we do now? Should we put this in the issues in the firmware first or do you do that?
