### ISSUE TITLE
[Bug]: Very Long Slow not an option in Lora settings

### ISSUE THREAD

**Issue by jesseas** [meshtastic/Meshtastic-Android#1361]
### What happened?

I tried to update my Heltic V3 to use Very Long Slow and it's not in the drop down under Lora settings (the other profiles are though). I was seemingly able to configure Very Long Slow through the web UI though. 

### App Version

2.5.3

### Phone

Samsung S22 ultra/ Android 14 Oct 1 2024 patch level

### Device

Heltec 3

### Firmware

2.5.4.8d288d5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by garthvh** [comment]
Very Long Slow was Deprecated in 2.5

**Comment by jesseas** [comment]
ok, thanks for the info, guess I missed that.
