### ISSUE TITLE
[Feature Request]: Implementation of MaterialYou Design for the Android client

### ISSUE THREAD

**Issue by GuiSousa135** [meshtastic/Meshtastic-Android#1378]
### Tell us your idea.

I would like to see the Meshtastic app for Android updated and modernized to MaterialYou Design, making the app more intuitive and beautiful: with tabs at the bottom of the screen, with easier to access radio settings, colorful graphs for metrics, signal quality, among other things.

The Android app has an old look, the theme is not consistent (it doesn't have black amoled mode), the "radio settings" option could be easier to access.

### Relevant log output

```shell

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jamesarich** [comment]
This is actually slowly being accomplished as views are being refactored and migrated to Jetpack Compose. Currently we're only levaraging the Compose Material (1.0) libraries, but once migration is complete this opens us up to migrating to Material3 and potentially MaterialYou (dynamic colors).
