### ISSUE TITLE
[Bug]: files missing

### ISSUE THREAD

**Issue by KubaMiszcz** [meshtastic/Meshtastic-Android#1379]
### What happened?

based on this first page:
[https://meshtastic.org/docs/development/android/](https://meshtastic.org/docs/development/android/)
there is no files in this directories, and this code wont work:
```
rm ./app/google-services.json
cp ./app/google-services-example.json ./app/google-services.json
rm ./app/src/main/res/values/curfirmwareversion.xml
cp ./app/special/curfirmwareversion.xml ./app/src/main/res/values/
```

### App Version

2.5.6

### Phone

POCO F5

### Device

T-Beam

### Firmware

2.5.9

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
that step is not needed. I've updated the docs to reflect that.
