### ISSUE TITLE
[Feature Request]: Option to follow the location on the map

### ISSUE THREAD

**Issue by Dtrieb** [meshtastic/Meshtastic-Android#1387]
### Contact Details

dtrieb

### Tell us your idea.

I would like to have a option to select which location (Meshtastic Device or Smartphone) used, and follow this on the map, too.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by b8b8** [comment]
You can already follow the smart phone position on the map by pressing the compass/target icon.

**Comment by Dtrieb** [comment]
> You can already follow the smart phone position on the map by pressing the compass/target icon.

Okay!

But I have always press the icon to reload.
And what's about the Meshtastic device as follow up?
