### ISSUE TITLE
[Bug]: Android 15 looses Bluetooth connection completely when app in background

### ISSUE THREAD

**Issue by Franselbaer** [meshtastic/Meshtastic-Android#1407]
### What happened?

Since Android 15 update on my Pixel 7 recently, the app looses bluetooth connection to T Echo while in background completely and it does not come back at all. Only if I re-open the app, click to "none connected" and then back to my device the connection comes back.

Background authorization is still set (double checked). Battery usage is 2-5% over the day. Seems to be something new in Android 15 and bluetooth...

### App Version

2.5.7 from Google appstore.

### Phone

Pixel 7a

### Device

T Echo

### Firmware

2.5.11

### Relevant log output

```shell
none
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
Some users are having Bluetooth issues with Android 15, while most work fine and I can't reproduce it myself. There's not much we can do from the app side to fix that.

**Comment by b8b8** [comment]
its def android and not the app. Im having problems with one of garmin watches as well. Also a pixel 7a.

**Comment by Franselbaer** [comment]
The thing is, the app tries to reconnect every 15 minutes if in background
and lost connection to pull everything new..Even that doesn't work well
anymore.

b8b8 ***@***.***> schrieb am Di., 19. Nov. 2024, 01:24:

**Comment by tavdog** [comment]
I believe I had found a fix in https://github.com/meshtastic/Meshtastic-Android/pull/1463
