### ISSUE TITLE
[Bug]: Intermittent crashes when clicking Traceroute

### ISSUE THREAD

**Issue by jeremiah-k** [meshtastic/Meshtastic-Android#1408]
### Contact Details

@Jack!

### What happened?

We're trying nodes in new areas so I've been running a lot of traceroutes lately.  It doesn't happen every time, but since upgrading to 2.5.9 this morning it's now crashed 3 times.

I haven't had issues at all with previous releases.

### App Version

2.5.9 F-Droid

### Phone

Pixel 6 Pro - GrapheneOS (Android 15)

### Device

T1000-E

### Firmware

2.5.12

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by madeofstown** [comment]
I'm experiencing this now also. Installed and tested this morning on my mobile node, seemed to be working fine. Now I'm back home and testing it with my G2 and it's crashing every time I run a traceroute.

**Comment by SimbimChimbetov** [comment]
Had it few times on RAK4631 but not 100% every trace route.
Also crashes on requesting position on Nodes with fixed Position that are manually set via remote admin.

Android 2.5.9
Firmware 2.5.11

**Comment by madeofstown** [comment]
I've now had it crash a couple times while requesting position as well.  Seems that if I force close the app and reopen it will work ok for a bit. Once the app starts crashing on traceroutes it will usually continue until I force close and reopen.

**Comment by madeofstown** [comment]
Might have something to do with the node menu refactor? Crashing when I request node info for an unknown node as well
