### ISSUE TITLE
###Default names with multiple # symbols

### ISSUE THREAD

**Issue by moxy-bc** [meshtastic/Meshtastic-Android#141]
Using the Android app (v0.9.02) with TTGO Meshtastic 0.9.1 creates channel names with multiple ### signs.  It is very hard to set it to a channel and have it stick.  It seems to add a # to the front each time.  After multiple reboots I finally got it to change, but there's a bug in the handling of names.  Not sure if it's in the Android App or the Meshtastic firmware
![IMG_20200827_175756](https://user-images.githubusercontent.com/1828944/91514579-f4089700-e89b-11ea-8c15-ffcec5a76924.jpg)

**Comment by geeksville** [comment]
ooh that sounds bad - thanks.

**Comment by geeksville** [comment]
alas - I can't figure out how to reproduce this (though obviously I believe your picture).  I'm releasing a new device load tonight, would you mind trying it and see if still shows this for you?

**Comment by dzaczek** [comment]
I have this same issue . It happen when i try change channel to open Default  then and wait few minutes and a aplication  asking me for upodate information after that i see the network i closed and name is "###Default-" . To simulate open network and change name to Default then restart esp32
![Screenshot_2020-09-07-23-43-14-736](https://user-images.githubusercontent.com/9393112/92448854-bd3e5500-f1a8-11ea-9913-8b0315917da1.jpg)
![IMG_20200908_094917](https://user-images.githubusercontent.com/9393112/92448858-bdd6eb80-f1a8-11ea-82a8-4f494a64325a.jpg)

**Comment by geeksville** [comment]
ooh thank you @dzaczek for hte great steps to repro.  I'm sure that will help a lot.

**Comment by geeksville** [comment]
problem turned out to be accidentally running UI handler code when the device disconnects/reconnects.
