### ISSUE TITLE
[Feature Request]: Custom map tile sources

### ISSUE THREAD

**Issue by stretchkerr** [meshtastic/Meshtastic-Android#1427]
### Contact Details

Zl3xlsimon@gmail.com

### Tell us your idea.

app/src/main/java/com/geeksville/mesh/model/map/CustomTileSource.kt contains additional tilesources not visible in the app. Many non-US users would like to be able to remove US-centric maps sources and add ones more relevant to their regions.

Can the map tileserver list be broken out into a user-accessible xml file, similar to how ATAK, and SWmaps do it? This would allow users to enter their own tileserver address, zoom limits, API key (if any).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
The unused map sources mentioned are experimental, not ideal for production use. The current map sources provide reliable, free, worldwide coverage.

Adding custom maps has become difficult to implement since Android 10 due to storage restrictions ([details here](https://github.com/orgs/meshtastic/projects/8?pane=issue&itemId=12006922)). If you have a solution, PRs are welcome!

**Comment by hayschan** [comment]
Upvote for this. Currently, all the data source in the Android Meshtastic app is not accessible from China's internet. They are all blocked by the GFW.

**Comment by Humble-Helper-96** [comment]
I was just creating a local custom map server using tileserver-gl and I would love to be able to point Meshtastic at it for a map source. 

This would also help solve issues for those in parts of the world who cannot access the listed map sources. They can spool up their own tileserver on simple hardware.  I know I am here asking for someone else to do the work as I don't know how to help but it would be nice if I could plug in a URL and point the Meshtastic app at the server. 

Example: 
Here is a public facing tileserver-GL instance:
https://vntilesgl.eofactory.ai/

It can serve XYZ tiles and it would be nice to drop this in:
https://vntilesgl.eofactory.ai/styles/basic/{z}/{x}/{y}.png

**Comment by jamesarich** [comment]
> I was just creating a local custom map server using tileserver-gl and I would love to be able to point Meshtastic at it for a map source. 
> 
> This would also help solve issues for those in parts of the world who cannot access the listed map sources. They can spool up their own tileserver on simple hardware.  I know I am here asking for someone else to do the work as I don't know how to help but it would be nice if I could plug in a URL and point the Meshtastic app at the server. 
> 
> Example: 
> Here is a public facing tileserver-GL instance:
> https://vntilesgl.eofactory.ai/
> 
> It can serve XYZ tiles and it would be nice to drop this in:
> https://vntilesgl.eofactory.ai/styles/basic/{z}/{x}/{y}.png

Boy are you in luck. This already exists.

![Screenshot_20251031-131112.png](https://github.com/user-attachments/assets/80eb6902-d537-4665-9ee1-92abc2a4b945)

![Screenshot_20251031-131336.png](https://github.com/user-attachments/assets/b6877be9-4bb4-4b36-9e19-e936cb514845)

![Screenshot_20251031-131129.png](https://github.com/user-attachments/assets/726d11fd-cdf0-4f71-876e-d592206933c5)
