### ISSUE TITLE
[Bug]: MQTT settings aren't saved

### ISSUE THREAD

**Issue by jimbolimbo3** [meshtastic/Meshtastic-Android#1428]
### Contact Details

jimbolimbo4@gmail.com

### What happened?

I can't save MQTT settings, in the video I show the bug.

https://github.com/user-attachments/assets/3527e0fb-116d-4003-b50c-d45c6db9fe08

### App Version

2.5.10

### Phone

Oneplus Nord 2

### Device

Seeed Card Tracker T1000-E

### Firmware

2.5.11.8e2a3e5 Beta

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caveman99** [comment]
You need to set radio region first. Also what firmware version is on the tracker?
