### ISSUE TITLE
[Bug]: Many translation error in french 

### ISSUE THREAD

**Issue by HB9HLI** [meshtastic/Meshtastic-Android#1434]
### Contact Details

hb9hli

### What happened?

Hi,  In the latest version, I have many translation errors in french, like mix with other languages. In English it's OK. The previous version don't have this problem. Other friends have same.Many thanks.

Dom. HB9HLI.

### App Version

2.5.10

### Phone

OnePlus 9 pro

### Device

Tbeam/t-echo 

### Firmware

2.5.9.936260f

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
https://developer.android.com/guide/topics/resources/multilingual-support#resource-resolution-examples

<img width="908" alt="2024-11-26 16 57 57" src="https://github.com/user-attachments/assets/3f7aa94d-199d-4f40-a9aa-7c53945a0832">

There are 196 untranslated words. Missing translations will use resource resolution above.

Contributions are welcome at: https://crowdin.meshtastic.org/android/fr

**Comment by Retidurc** [comment]
Hmm, i'm not sure it's the same issue @HB9HLI was talking about, but a lot of french strings where overriden by another language.

It seems someone on crowdin need to go back to each string one by one to fix the translation 

![Image](https://github.com/user-attachments/assets/6f5172a4-20db-4617-bd04-07ee9eb44230)
Here, for example, all previous variation are good, except from the last one.

Is there any way to mass remove the wrong contributions ?
