### ISSUE TITLE
Signal and battery indicator for powered-off Tbeam

### ISSUE THREAD

**Issue by DDVanMS2018** [meshtastic/Meshtastic-Android#145]
In the list of units for the App, the time is behaving like it's connected, but the tbeam is off.  The map is fine, the powered-off unit doesn't display.  Is this normal behavior?  I think it should show a "?" for a unit that is off or unreachable.  My first issue post, be kind.  

Thanks.

App v0.9.05
tbeam 1.0-US/0.9.3
T-Beam V1.1 w/ NEO-6M
T22_V1.1 20191212

**Comment by DDVanMS2018** [comment]
I also encounter the "?" for the device that is on and connected via BT.  I get the time for the device that is off.  

The notification often says "Conected: 2 of 2 online" when I only have 1 powered-on.

**Comment by lgoix** [comment]
@geeksville if devices is powered-off, why the phone is still receiving its infos ?

**Comment by andrekir** [comment]
this should be resolved. if you find this error still occurs in recent app & device firmware versions please reopen this issue.
