### ISSUE TITLE
[Feature Request]: Add option to hide/disable emoji reactions

### ISSUE THREAD

**Issue by sycophantic** [meshtastic/Meshtastic-Android#1453]
### Tell us your idea.

I'd like the app to behave before this emoji reactions feature was added. Please add an option to disable seeing them.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sycophantic** [comment]
Guess it's time for a fork.

**Comment by sycophantic** [comment]
It's unneeded mesh traffic.

**Comment by RCGV1** [comment]
A single emoji is much less data than a text message. Also this feature has already existed on the iOS app now android users can also send emoji reactions.

**Comment by b8b8** [comment]
It's also a feature in every other messaging app.

**Comment by sycophantic** [comment]
Metastatic isn't "every other messaging app". We don't need emoji reactions for emergency communications.

**Comment by deadman96385** [comment]
It would be nice if it was a toggle, so it can be removed to not clutter up space in the UI. Default the switch to be on to not break current behavior and expectations. I don't agree with the whole just because other apps have it you need it as well philosophy. But I can see why some people may like the feature.

**Comment by sycophantic** [comment]
> It would be nice if it was a toggle, so it can be removed to not clutter up space in the UI. Default the switch to be on to not break current behavior and expectations. I don't agree with the whole just because other apps have it you need it as well philosophy. But I can see why some people may like the feature.

That's all we need is the toggle.

**Comment by sycophantic** [comment]
Can someone explain how this is ok? This is why I want a toggle.
![Screenshot_20241209-212855](https://github.com/user-attachments/assets/a89006f2-6d38-41b8-ac8d-4fcc5bb07270)

**Comment by garthvh** [comment]
You are using a global public channel, you can't control what he content of messages sent on a globally public channel. This is a message like any other, and is not new functionality.

**Comment by sycophantic** [comment]
Can someone explain how this is ok? This is why I want a toggle.
![Screenshot_20241209-212855](https://github.com/user-attachments/assets/a89006f2-6d38-41b8-ac8d-4fcc5bb07270)

**Comment by sycophantic** [comment]
@garthvh why is so hard to just add a toggle in the application?
