### ISSUE TITLE
[Feature Request]: Add show Node on long press menu

### ISSUE THREAD

**Issue by Dtrieb** [meshtastic/Meshtastic-Android#1461]
### Contact Details

dtrieb

### Tell us your idea.

I'd like the app to have a option in the long press menu of the Node to show this Node on the Map in the App.

![Screenshot_20241213-105139](https://github.com/user-attachments/assets/98bc420e-e3c1-47a6-8fd9-fe02000f7c6a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
Duplicate of #543
