### ISSUE TITLE
[Feature Request]: request neighbor info

### ISSUE THREAD

**Issue by cracky22** [meshtastic/Meshtastic-Android#1468]
### Contact Details

martinblieninger2208@gmail.com

### Tell us your idea.

request neighbor info over Lora radio from other nodes 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by liamcottle** [comment]
As far as I'm aware, the firmware doesn't allow you to request neighbour info

**Comment by cracky22** [comment]
okay thanks. can you leave the issue open or should I reopen it when support is available?
https://github.com/meshtastic/firmware/issues/5581
