### ISSUE TITLE
No available bluetooth devices found on "Select radio below" list.

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-Android#147]
On a Samsung Galaxy S2 with Android 7 with the Meshtastic Android App v0.9.05, none of my mesh devices show on the list of available devices within the app but they do show up when I go into bluetooth settings.

I clicked the report bug button at Aug 29 at around 5:17pm.

Screen shots:

![Screenshot_20200829-171857](https://user-images.githubusercontent.com/12804989/91648485-5d63e380-ea1d-11ea-8c00-12288dd0d7e6.png)
![Screenshot_20200829-171919](https://user-images.githubusercontent.com/12804989/91648509-9439f980-ea1d-11ea-8af6-7e8180b1bda3.png)

**Comment by geeksville** [comment]
Interesting that the devices are showing up in the system BLE scan screen but not the app screen.  Did you grant the app location access? (without that Android doesn't allow apps to see BLE devices)

**Comment by mc-hamster** [comment]
Yes, app location access is granted.

![Screenshot_20200829-122317](https://user-images.githubusercontent.com/12804989/91650208-9c039900-ea31-11ea-92b2-8cb0c0ed99f2.png)

**Comment by geeksville** [comment]
hmm - I haven't received a report yet from a samsung galaxy yet.  Can you try rebooting your phone and running meshtastic (the google bug reporter thingy may wait up to 2 days otherwise)

**Comment by mc-hamster** [comment]
Resent @ 1:48pm

**Comment by lgoix** [comment]
I'm having the issue, just switched to another tab in the app and back to setting make the devices appear

**Comment by mc-hamster** [comment]
> I'm having the issue, just switched to another tab in the app and back to setting make the devices appear

I tried that on my end, no go.

**Comment by mc-hamster** [comment]
Everything seems to work as expected.
