### ISSUE TITLE
[Feature Request]: Add short Name under emojis if choose.

### ISSUE THREAD

**Issue by Dtrieb** [meshtastic/Meshtastic-Android#1479]
### Contact Details

dtrieb

### Tell us your idea.

If you change the short Name to a emoji in the android app you can't distinguish people (in the chat list) if they use the same emojis.

![Screenshot_20241215-221633](https://github.com/user-attachments/assets/9877d1df-c02b-4883-94a3-f41593e27d3f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by garthvh** [comment]
When you change your shortname to an emoji that is now your shortname.

**Comment by garthvh** [comment]
What you really want is something like this on iOS
![IMG_3631](https://github.com/user-attachments/assets/f674fa71-03e8-48a3-9dbc-c4bbf6c23f31)

**Comment by Dtrieb** [comment]
Yes because if I am on a full MQTT Channel there will be a huge chance to have 2 or more same emojis.
