### ISSUE TITLE
[Bug]: location changes on its own

### ISSUE THREAD

**Issue by epragalakis** [meshtastic/Meshtastic-Android#1487]
### Contact Details

here on github

### What happened?

updating the coordinates position on a fixed location while everything else is disabled (eg: smart position, gps etc) updates it to something random.

for example after updating the lon to 4.23.... it updates it to 4.22....

I've tried different approximate locations and the result its always placing me a few km north or south from the coords I'm giving it (the coords are correct and are taken from google maps).

At times, it updates them correctly and I can validate that on the map that is in the app, but after a while it changes back (this happened a couple of times but its not consistent)

### App Version

2.5.12

### Phone

samsung android12

### Device

RAK4631

### Firmware

latest beta

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caveman99** [comment]
set location_precision to 'precise'
