### ISSUE TITLE
[Bug]: Message input auto-capitlization

### ISSUE THREAD

**Issue by madeofstown** [meshtastic/Meshtastic-Android#1492]
### Contact Details

@madeofstown

### What happened?

In previous app versions when typing a message, the first letter of each sentence was automatically capitalized. This behavior is expected and is the default for almost all text entry boxes. A few versions ago (not sure exactly when) that changed and first letters are no longer capitalized automatically.

### App Version

v2.5.13, v2.5.14, v2.5.15

### Phone

Pixel 7a, GrapheneOS

### Device

T1000e, Linux Native Portduino

### Firmware

V2.5.15, v2.5.16

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by madeofstown** [comment]
![Screenshot_20241220-052331](https://github.com/user-attachments/assets/64524700-7707-44ca-9879-49f6eaad99da)
It's not a keyboard settings issue. Message input for SMS messages automatically capitalizes as expected

**Comment by andrekir** [comment]
Good catch, this will be fixed in the next release (fixed in e924f274f150487a13e386a3774729b4edca93bf).
