### ISSUE TITLE
[Feature Request]: Request Position using non-primary channel

### ISSUE THREAD

**Issue by IlyaMZP** [meshtastic/Meshtastic-Android#1507]
### Contact Details

ilya@mango.vg

### Tell us your idea.

I'd like the app to be able to request a node position using non-primary channel. Currently "Request position" only uses the primary channel.
If both nodes have secondary private channel, it could be beneficial if said channel has different location precision than the primary one.

This would allow nodes to have a public primary channel and still be able to share precise location privately.

Meshtastic CLI app has this option implemented with `--ch-index 1` argument.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrekir** [comment]
> Currently "Request position" only uses the primary channel.

This is incorrect. All requests use the channel where the remote node was heard from (same channel indicated in the node list).

This is how it is handled in the firmware and there is no plan to add an option to manually select the channel.
