### ISSUE TITLE
can not change name or send messages

### ISSUE THREAD

**Issue by datadrian** [meshtastic/Meshtastic-Android#178]
Greetings, I'm running the android app on an acer r11 chrome book, didnt have this issue yesterday but today I do, this issue is occurring in both released version and the beta version.

App connected to heltec 1.0-us/1.1.0

can not change name and can not send messages.
I see some of the incoming messages
I can type in the send message text box, but upon hitting enter no message sends. Worked fine yesterday.

I have submitted a bug report.

Thanks! and great work!!!

**Comment by geeksville** [comment]
alas - the chromebook bluetooth stack for android is notoriously buggy.  I'll take a look at this in a couple of weeks after some other work items are finished.

**Comment by datadrian** [comment]
Understood, thank you.

Adrian Stucker
513.341.LENS

**Comment by andrekir** [comment]
closing. if this issue is still present please reopen.
