### ISSUE TITLE
Feature request: Add meshstatic to fdroid.org

### ISSUE THREAD

**Issue by improvethings** [meshtastic/Meshtastic-Android#184]
This is simply a feature request, can you please also push meshstatic to [fdroid](https://f-droid.org/) those of us who don't use/trust the Google Play Store?

Thanks in advance!

**Comment by geeksville** [comment]
alas - not currently.  The fdroid terms of service do not allow including analytics (and analytics is too useful to turn off - though we do let people opt out).  Apparently ACRA analytics are acceptable - but someone would have to volunteer to add ACRA to the code and host the ACRA server.

We do periodically upload apks to github though.

More info here: https://github.com/meshtastic/Meshtastic-Android/issues/6#issuecomment-599169031
