### ISSUE TITLE
Integrate user manual from @qurm

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-Android#189]

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/if-anyone-wants-to-make-a-userguide-or-two/245/5

**Comment by sachaw** [comment]
This has been completed in https://github.com/meshtastic/Meshtastic/pull/29, the wiki page can be removed, and likely turned off at this point

**Comment by andrekir** [comment]
done.
