### ISSUE TITLE
Issue: App Start, and Channel Menu

### ISSUE THREAD

**Issue by JamesM92** [meshtastic/Meshtastic-Android#192]
Please disregard, looks as though this wasn't on the latest version.
/////////////////////
I just loaded the new app on 2 different phones and found the same issue on both.

1) When starting the app, if the metastatic device is off, the app says it isn't seeing the device and is scanning to find it. But it never registers that the device is available until you exit and return to the app. 

2) once you have selected the device it doesn't give any indication it was successful, or that you need to click the metastatic icon to move to the next menu.

3) the channel page is blank, it shows only the title bar, and a white page. so I'm unable to setup the channels at this time.

////Device and Firmware Info////
Phone 1: SAMSUNG GALAXY EXPRESS 3
Model: SAMSUNG-SM-J120A
Android Version: 6.0.1
Metastatic Version:1.0.0
Device: LILYGO® TTGO Meshtastic T-Beam V1.1
Firmware: firmware-tbeam-US-1.1.4

Phone 2: SAMSUNG GALAXY A10e
Model: SM-A102U1
Android Version: 10
Metastatic Version: 1.0.0
Device: LILYGO® TTGO Meshtastic T-Beam V1.1
Firmware: firmware-tbeam-US-1.1.4

**Comment by geeksville** [comment]
no worries - btw - you might dig our forum also: meshtastic.discourse.group
