### ISSUE TITLE
latest releases are not published on GitHub

### ISSUE THREAD

**Issue by khimaros** [meshtastic/Meshtastic-Android#200]
as a user of AOSP android, i have no access to the Play store. meshtastic is also not being published to F-Droid.

for these reasons, i am relying completely on the GH releases. the most recent alpha and beta builds have not have not been published to GH which makes it difficult for me to test new releases.

**Comment by geeksville** [comment]
ok - sorry about that - I'll push a build later today to github.  I've been kinda lazy about pushing bins there.

Alas - I can't list this project on f-droid because their TOS don't allow analytics (which this project includes as an optional feature).

**Comment by geeksville** [comment]
here you go https://github.com/meshtastic/Meshtastic-Android/releases/tag/1.1.8

**Comment by khimaros** [comment]
thank you!
