### ISSUE TITLE
Add the ability to clear/delete messages 

### ISSUE THREAD

**Issue by nasprouse** [meshtastic/Meshtastic-Android#201]
Currently there is no ability to delete individual  messages from the thread or clear all messages from the thread.

Adding this would allow messages to be cleared so a user could start fresh for the day/ event or to correct erroneous messages that clog the thread.

**Comment by geeksville** [comment]
good idea

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/1-2-31-feedback/3370/1
