### ISSUE TITLE
Getting "Application too old" error msg

### ISSUE THREAD

**Issue by ChromeBlue** [meshtastic/Meshtastic-Android#210]
I've updated both the Android app and the firmware on the device. (Both were already most current) and still getting error.

Using Pixel 3XL with Android 11.

**Comment by geeksville** [comment]
Based on your forum post I think this is now solved right? (by updating to the beta).  If not, I'll happily reopen.

**Comment by ChromeBlue** [comment]
Yes, the issue has been resolved.  Thank you.
