### ISSUE TITLE
Add the ability to increase hop_limit to packet sent from Android APP

### ISSUE THREAD

**Issue by SQ7HIT** [meshtastic/Meshtastic-Android#219]
Adding this would allow text messages to be send in larger meshes.

**Comment by phayes** [comment]
Would it be possible to fund development of this?  This is something we critically need.

**Comment by geeksville** [comment]
Alas, my queue is full for the next couple of months with other Meshtastic tasks.  Perhaps if you ask on the forum you might find someone who has time to make this change.

**Comment by andrekir** [comment]
keeping settings simple and sticking to defaults for now. closing.
