### ISSUE TITLE
Message history disappears

### ISSUE THREAD

**Issue by DylanHoen** [meshtastic/Meshtastic-Android#231]
When I quit the meshtastic app, restart my phone, and then start the meshtastic app again, my message history disappears. This has been happening for the last few app releases. I don’t know about older versions, but I think it used to keep message history for months.

**Comment by geeksville** [comment]
hmm - i'm having a problem reproducing this.  when you say "quit meshtastic app" do you mean force-quitting it from android?  In that case we might not have written the latest message history to our settings (we only dump to disk when we lose connection to the local node)

**Comment by geeksville** [comment]
oh never mind - I thought of how this could happen
