### ISSUE TITLE
hopLimit is not exposed in DataPacket

### ISSUE THREAD

**Issue by paulmandal** [meshtastic/Meshtastic-Android#235]
`hopLimit` is not exposed on the `DataPacket` used by applications integrating with the `MeshService`. I'd like to set different `hopLimit`s for different types of messages in my application.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/atak-for-hikers-signed-meshtastic-plugin/2229/9

**Comment by paulmandal** [comment]
https://github.com/meshtastic/Meshtastic-Android/pull/252 should resolve this

**Comment by geeksville** [comment]
fixed by @paulmandal
