### ISSUE TITLE
Misc app improvement ideas

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-Android#24]
This post includes both device and app feature ideas (but mostly for the app side).

I'm making an issue here and we should think about this/start work on them after the 1.0 release is out.

https://meshtastic.discourse.group/t/various-function-suggestions/161/7

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/various-function-suggestions/161/7

**Comment by Xanuman** [comment]
This project is perfect for use as a gps tracker. You can track the whereabouts of relatives (children and the elderly) or pets.

In particular, I plan to use Meshtastic to control the flock of sheep. In this regard, I had a suggestion for improving the Android application:

The ability to configure geofences in the application. For example, we indicate a network node and assign it a geofence. When a node leaves the geofence, the application gives us an alarm.

**Comment by JamesM92** [comment]
I believe its been mentioned on the forum but not here. But the ability to send messages to an individual and not the entire group would be useful.

**Comment by andrekir** [comment]
many features listed were added since and this feature request cycle is done. closing.
