### ISSUE TITLE
Nodes snr, bearing and position in nodes tab

### ISSUE THREAD

**Issue by IZ1IVA** [meshtastic/Meshtastic-Android#240]
I believe it might be useful to show the last computed snr, bearing and position for each node in the nodes tab.

To avoid clutter the whole tab could have two selectable "pages": one showing owner, distance, bearing and last-heard time, another showing owner, position, altitude, batteryLevel.

Switching between pages could perhaps be implemented by double-tapping anywhere in the nodes list.

**Comment by andrekir** [comment]
this is done. bearing was added in the map markers.
