### ISSUE TITLE
It is mandatory to have Mapbox ACCESS TOKEN?

### ISSUE THREAD

**Issue by hpsaturn** [meshtastic/Meshtastic-Android#246]
Hi everyone, I want try to understand the Android client of Meshtastic, in order maybe to help with the project, but I have the same issue that give the [Github workflow](https://github.com/meshtastic/Meshtastic-Android/runs/1896852972) (continous integration badge). To the point:

```java
Meshtastic-Android$ ./gradlew assembleDebug
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :app:compileDebugAidl FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugAidl'.
> Could not resolve all files for configuration ':app:debugCompileClasspath'.
   > Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.0.
     Required by:
         project :app
      > Could not resolve com.mapbox.mapboxsdk:mapbox-android-sdk:9.6.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-android-sdk/9.6.0/mapbox-android-sdk-9.6.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-android-sdk/9.6.0/mapbox-android-sdk-9.6.0.pom'. Received status code 401 from server: Unauthorized

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s
1 actionable task: 1 executed
```
Is mandatory to have Mapbox ACCESS TOKEN?

Thanks

**Comment by geeksville** [comment]
re: maybe helping
Cool!  Much appreciated!

re: mapbox token
sadly yes it is ;-).  But it is easy to get one.  I just added some instructions (see commit above - not yet merged into master)

Also this related comment: https://github.com/meshtastic/Meshtastic-Android/issues/218 (which I still haven't gotten around to)

If you have any other problems questions getting things building, you can also reach the other geeks on our slack chat (there is a sticky link in the development subsection of our forum)
