### ISSUE TITLE
Some node is sending 'old style' position messages

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-Android#247]
Probably(?) the android app version 1.1.44 when trying to "fill in" and provide GPS position for a local node that doesn't have a GPS.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/warningignoring-old-position-user-message/2503/10

**Comment by andrekir** [comment]
this issue is resolved in later versions. closing.
