### ISSUE TITLE
Location & Node suggestion 

### ISSUE THREAD

**Issue by CasualArclamp** [meshtastic/Meshtastic-Android#251]
Will you be adding a feature to request the location of another node? And to request a node network refresh?

**Comment by geeksville** [comment]
Implicitly the oled UI already does this.  If you scroll through to look at
a node it sends a message to that node requesting a fresh position.  But a
UI in the Android app is a good idea.

(Sent from a phone - please ignore typos)

**Comment by clavo2** [comment]
Any push/pull query update options, IMO, are a plus for the app.  There can always be an option to enable/disable the function.   It's kinda the point of having an app.   Not being tethered to a 1" screen that may be rooms away, on the roof, etc... Love the last 2 versions.  Most stable I've seen in my test setup so far.  Thanks.
