### ISSUE TITLE
Overlay problem for debug and advanced settings screens

### ISSUE THREAD

**Issue by apt105** [meshtastic/Meshtastic-Android#256]
When viewing the advanced settings and debug screens, the previously visited page is still visible underneath. 

https://meshtastic.discourse.group/t/the-last-1-1-release-android-app-1-1-50-is-up-for-alpha-testers/2714/2?u=apt105

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/the-last-1-1-release-android-app-1-1-50-is-up-for-alpha-testers/2714/5
