### ISSUE TITLE
autobug - 'crash' on switching between devices

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-Android#26]
from @erikthev-king

> wow! upgraded to 0.6.0 an hour ago and had a chance to play around with 2 tbeams. Perfect brew! Crashed once while swaping phone connection over from one tbeam to the other one but I guess it was my phone’s bluetooth messing up. Hope you got the crash report, Kevin.

[com.geeksville.mesh_issue_2a12c7f9d75db78e3f3f9648aff2177a_error_session_5EAFBD9D0204000177D962CEF307FD08_DNE_0_v2.log](https://github.com/meshtastic/Meshtastic-Android/files/4575505/com.geeksville.mesh_issue_2a12c7f9d75db78e3f3f9648aff2177a_error_session_5EAFBD9D0204000177D962CEF307FD08_DNE_0_v2.log)

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/android-app-new-releases/78/33

**Comment by geeksville** [comment]
fixed in 774ab65ece6f5c8b2c298d5626e4826d5cd123e3

**Comment by eriktheV-king** [comment]
Great ! thumbs up ! Thanks !
