### ISSUE TITLE
Add a confirmation dialog for firmware update?

### ISSUE THREAD

**Issue by Xanuman** [meshtastic/Meshtastic-Android#270]
This is a very unpleasant situation for me.
The android app started uploading firmware 1.2.17 without my command.
Smartphone: Xiaomi Redmi 7a
Android 10

I admit that I could accidentally press the firmware update button. But it would be nice with such a responsible procedure to make a dialog box for confirming the operation. Or, by other means, make it so that this operation cannot be done by accidental pressing.

**Comment by geeksville** [comment]
a button press is required to start a firmware update.

**Comment by andrekir** [comment]
#372
