### ISSUE TITLE
Nodes info discrepancies between app and device display

### ISSUE THREAD

**Issue by IZ1IVA** [meshtastic/Meshtastic-Android#277]
It's been a while since I first noticed that most nodes are reported in the app as missing position, SNR, last heard or a combination of those. But by checking the device display, I could see all those information, confirming perfect reception. Plus, some of these infos were actually different than those presented in the app.

This makes it harder to debug a mesh, sending messages across, tracking devices, etc. as the mesh seems not to be working while in fact it is!

**Comment by andrekir** [comment]
a lot has changed since this was opened, but starting from app [release 1.2.52](https://github.com/meshtastic/Meshtastic-Android/releases) NodeInfo `user`, `position` and `lastHeard` from device and app will match.

**Comment by andrekir** [comment]
@IZ1IVA is this issue resolved?

**Comment by IZ1IVA** [comment]
> @IZ1IVA is this issue resolved?

I've done limited testing, but apparently it has, thanks very much!
