### ISSUE TITLE
Duplication of messages

### ISSUE THREAD

**Issue by KiwiHC16** [meshtastic/Meshtastic-Android#294]
I have 4 TBeam equipments all in the same room for tests.
Android App 1.2.45

All are with 5V to keep them awake.

One (c480) is connected to a linux system.
One (c500) is connected to Android App in BLE.

If I send a message from c480:
```
 meshtastic --sendtext "TYTY"
```
I get 2 messages TYTY on the android Application.
All TBeam print TYTY on their screen.

If I send uniquely to the c500 / Android:
```
meshtastic --sendtext "Tata" --dest \!f244c500
```
Then only the receiver print on the screen the message but the Android App show 2 messages.
In the debug page of the android App, I see only one message.

If I connect c500 on a RPI3 and collect messages with this code:
```
import meshtastic
from pubsub import pub
import time

def onReceive(packet, interface): # called when a packet arrives
    print(f"Received: {packet}")

pub.subscribe(onReceive, "meshtastic.receive.text")

interface = meshtastic.SerialInterface("/dev/ttyUSB0")

while 1:
        time.sleep(1)
        print(".")

```

Then I receive only one message.

If I keep the sender and the receiver, I still have duplication at App Level.

All tests tend to show that the App duplicates the messages.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/android-app-1-2-45-ready-for-brave-alpha-testers/3793/5

**Comment by andrekir** [comment]
@KiwiHC16 can you confirm if this issue is still present on newer versions of the app? I could not reproduce it on ver 1.2.51
