### ISSUE TITLE
BLE issue

### ISSUE THREAD

**Issue by KrazyKerbalnaut** [meshtastic/Meshtastic-Android#297]
I have an issue where I can pair and usually talk on a network from the android app for about 5 or so minutes. After that, it is hit or miss, even though Bluetooth on the devices connecting to the network have remained on the whole time.

It seems that once the LoRa device goes into sleep mode and you switch apps, the BLE on the app no longer registers the device as connected. And getting it to reconnect without restarting the LoRa device is next to impossible. Occasionally, when the LoRa device wakes up, whether it receives a message or it's timer expires, if you time it just right, you can get the app to re-establish a BLE connection and start using it normally again.

Honestly, it's kind of maddening. I can use if fine, then all of the sudden, I can't communicate over the network. The devices are all still receiving messages from one device and work normally, but the issue seems to be related to the connection on BLE from the android app to the LoRa device.

I'm currently using the following devices:
Phone 1, BV9900Pro
Phone 2, Samsung Galaxy S9
LoRa Devices, Heltech WiFi LoRa 32 v2's

**Comment by KrazyKerbalnaut** [comment]
Haha, I just mentioned it.

**Comment by andrekir** [comment]
any updates on this? sounds a lot like the EPS32 sleep behavior rather than a Bluetooth issue
