### ISSUE TITLE
JsonReader.setLenient

### ISSUE THREAD

**Issue by DarrenKS227** [meshtastic/Meshtastic-Android#302]
When I try to use android studio 4.1.2 to open Meshtastic-Android.zip
When I run the android app to test. I meet 2 errors. I want to ask where can get ''JsonReader.setLenient''

Thank for help.

![image](https://user-images.githubusercontent.com/91327123/139538745-cd0d40a0-2871-4a56-9d8d-142f1d60dd77.png)
![image](https://user-images.githubusercontent.com/91327123/139538751-e89bef0e-36d5-4cd5-8015-53b27f2cdb01.png)

**Comment by andrekir** [comment]
did you follow the [build instructions](https://github.com/meshtastic/Meshtastic-Android#build-instructions)? do you have a proper `./app/google-services.json`?
