### ISSUE TITLE
Cannot modify name: keyboard arrow has no effect

### ISSUE THREAD

**Issue by prampec** [meshtastic/Meshtastic-Android#314]
As there is no "Apply" button near the "Your Name" filed, I assume, that it will apply the change upon keyboard "enter" key. Now, on Android 8.1 I see an icon "send" (arrow pointing to the right) instead of the enter key.
Pressing this key has no effect on applying name change.

No error, or debug message can be seen.

**Comment by andrekir** [comment]
if you are using android app 1.2.50 it is a bug #311 and should be fixed on the next release
