### ISSUE TITLE
Documentation issue: Android might not connect www.meshtastic.org links to the app

### ISSUE THREAD

**Issue by prampec** [meshtastic/Meshtastic-Android#315]
I have installed the app to my Android 12 phone and the channel links are opened within the browser, not by the Meshtastic app. The solution was to manually add "Open by default" link to the app.
See attached image.
![Screenshot_20211201-192929](https://user-images.githubusercontent.com/10376327/144315403-3987ca27-8186-4f2d-b46b-ac2d49e9952f.jpg)

**Comment by prampec** [comment]
(Would be nice to provide an "enter connection info" option to be used instead of automatic link processing.)

**Comment by andrekir** [comment]
(ref #188) in-app QR code scanner added in version 1.2.51 plus detailed step-by-step on how to open and share channel links: https://meshtastic.org/docs/software/android/android-usage#join-a-channel

**Comment by prampec** [comment]
Sorry, but I cannot see this very case covered by the documentation.
(QR code scanner can be a great solution to override this problem. I will check.)

**Comment by prampec** [comment]
Sorry didn't found the "Troubleshooting" pulldown. Now I believe the documentation covers this issue.
