### ISSUE TITLE
Add a settings screen that lets use change any of the RadioConfig parameters

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-Android#34]
i.e. to let them change sleep behavior (possibly put just a gui for "sleep time" in seconds/minutes)

comment from @sensorsiot

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/a-few-considerations-on-protobufs/729/2

**Comment by SensorsIot** [comment]
Hi Kevin,

I hope everything is well on your side. I just wanted to send you a document I got from one of my viewers. If you look at page 9, you see my video about Meshtastic as a strategic weapon. First, Naomi and the Chinese and now the American. Just the Russians are lacking…

I feel like Einstein, who did not like what they did with his discoveries…

Regards

Andreas

**Comment by andrekir** [comment]
keeping settings simple and sticking to defaults for now. closing.
