### ISSUE TITLE
mapview shows nodes with incorrect position.timestamp

### ISSUE THREAD

**Issue by mchisari** [meshtastic/Meshtastic-Android#348]
I believe that in networks like Meshtastic, giving no information is better than a false one. 

GPS data can be old, because you've heard the remote node long ago, or because it is currently unable to get fix - maybe it relies on phone GPS because it hasn't one on its own. To avoid mistakes old GPS data could be discarded, but I think there's a better way to handle this.
A device could send an update saying “half an hour ago I was at…” which is better that than saying “I believe I’m at…” or  “I don’t know where I am now”.

So, I propose that:
- When a device shares its position, it adds a timestamp stating when that position was taken
- Every device receiving it should store GPS timestamp with coordinates, along with a "received" timestamp
- This information "xxx minutes ago", relative to GPS timestamp, should be displayed by device with direction and distance of the other node; should also be shown on Android map of other users.
- The "received" timestamp should instead be shown in node list, both for device and Android app, so as to know when it was last heard.
At the moment the map and node “time” can be different because map uses time from position packet and node from nodeinfo packet. The logic instead should be: for each node store GPS position with its timestamp, and store last heard timestamp regardless of the type of received packet.
This would be more intuitive and informational.

**Comment by andrekir** [comment]
this is already solved.
