### ISSUE TITLE
Don't start service if no radio is paired

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-Android#36]
See associated discussion thread: (started by @brianczapiga)

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/android-app-service-running-but-i-dont-have-a-radio/285/7

**Comment by geeksville** [comment]
okay - thanks for the report @brianczapiga.  This fix will go out in tomorrow's build (but initially only to alpha/beta testers - If you'd like to join one of those groups you can get it then.  Otherwise it will go to everyone a few days later)

**Comment by brianczapiga** [comment]
Wow, that was really quick. Were you also able to add an exit function? I didn't see one in the referenced commits.

**Comment by geeksville** [comment]
yes - though I chose not to call it exit.  In the device list there is now
a "None" device - because I think that is a cleaner UX.  If you select that
the services are stopped so there is no background code (so the app gets
fully suspended like any other 'activity only' app).
