### ISSUE TITLE
Feature request: allow Meshtastic app to talk to public mqtt server and participate in mesh

### ISSUE THREAD

**Issue by Vertikar** [meshtastic/Meshtastic-Android#361]
Very high level idea, and I haven't got the knowledge on how to do it, but would be great if when a device has internet connectivity, it could participate in an existing mesh over mqtt or another transport.

This way if you're somewhere with internet and haven't got  a Meshtastic device you could still send and receive messages.

**Comment by andrekir** [comment]
interesting idea. unfortunately this is largely incompatible with the core interface foundation, based on direct access to a device. MQTT has just a tiny part of all data exchanged (packet traffic).

something similar that is supported (and is on my roadmap) is adding the TCP interface.
