### ISSUE TITLE
No RX position in rangetest.csv

### ISSUE THREAD

**Issue by kingoffoxes** [meshtastic/Meshtastic-Android#380]
Using 1.2.58 paired with the receiving node (tbeam 1.2.55.9db7c62) i am able to export the rangetest.csv on my phone (Galaxy J3 - 5.1.1) but when i open the file
[rangetest1.csv](https://github.com/meshtastic/Meshtastic-Android/files/8103729/rangetest1.csv)
the RX fields are blank. 
This was fine when using the web version before that feature was removed, now on android i am having this issue so i think its the app - not the node. 
Payload is reported as "payload" instead of the sequence number.

**Comment by andrekir** [comment]
> This was fine when using the web version before that feature was removed

fiy range test plugin wasn't removed, but looks like the file location changed https://github.com/meshtastic/Meshtastic/issues/232
