### ISSUE TITLE
Add NFC app intent to allow scanning NFC tags with channel URL

### ISSUE THREAD

**Issue by 5rxp** [meshtastic/Meshtastic-Android#397]
Pretty self explanatory! 

I tried writing the channel URL to an NFC tag, but when I scan it, it only allows me to choose a browser app to open the link. I double checked the current open by default settings, and they are enabled for www.meshtastatic.org.

I would add this myself but I have never written android apps, only web apps, so I do not have a setup for testing such a change to the code.

Here is a stackoverflow describing the issue and has the correct app intent code for the manifest file:

https://stackoverflow.com/questions/41678720/android-nfc-tag-with-url-opening-browser-not-my-app

Thank you all for your hard work!

**Comment by andrekir** [comment]
I have reservations about this since android URI handling is very unreliable. all qr code scanning moved in-app for this reason and is the recommended method to share channels.
