### ISSUE TITLE
Feature Request - Node info/See how the node is reached/how many hops

### ISSUE THREAD

**Issue by rwcts** [meshtastic/Meshtastic-Android#402]
When looking on the android app on the node listings, allow users to see immediately or by clicking (or press and hold) and show how that device communicates back to you. Example. If node 1 is the node you are connected to, then node 2 is 10kms away that you can reach directly and node 3 is 20 km away that you cannot reach directly but you hear and communicate with it through Node 2. 

Allow it to display how it's being heard/how many hops and through who.

**Comment by garthvh** [comment]
This is not available data with the current flood routing algorithm
