### ISSUE TITLE
Feature Request - Message confirmation

### ISSUE THREAD

**Issue by rwcts** [meshtastic/Meshtastic-Android#403]
When sending a message have nodes confirm receipt. As of this moment, it only shows a check box on the message. A confirmation would allow a long press on the message and a popup showing who confirmed receipt. I don't know how this would play a part in the if_router functionality but thought it would be nice to have.

**Comment by garthvh** [comment]
This may be possible once we have upgraded to 1.3, right now with flood routing we do not know who ACK'ed a broadcast message.  ACK's for DM's are from the node the DM was sent to.
