### ISSUE TITLE
Feature request: Implement ability to scan channel settings from image

### ISSUE THREAD

**Issue by DarkFIxED** [meshtastic/Meshtastic-Android#425]
As a user I want to be able to share generated QR code with my teammates and he are able to open it via Meshtastic app. Currently I should scan it via another device through screen.

**Comment by andrekir** [comment]
you can use the camera ("scan" button) from the app or the channel URL (ie.: https://www.meshtastic.org/d/#CgUYAyIBAQ) from anywhere else to join channels, check: https://meshtastic.org/docs/software/android/android-usage#join-a-channel

**Comment by andrekir** [comment]
please search issues to verify the bug or feature has not been raised before. if you have questions join us at https://meshtastic.discourse.group or Discord: https://discord.gg/ktMAKGBnBs
