### ISSUE TITLE
Bug: Channel settings from QR code opens in browser, not meshtastic app

### ISSUE THREAD

**Issue by DarkFIxED** [meshtastic/Meshtastic-Android#426]
Used device: Xiaomi Mi 11 Lite, MIUI 13.0.1, Android: 12.

Steps to reproduce:
1) Open Meshtastic app and connect to device via Bluetooth.
2) Go to Channel settings tab, unlock changes and try to scan QR code.

Expected result:
Channel settings will be scanned and handled in app.

Actual result:
Link opened in Chrome browser.

Additional info:
All required permissions to open appropriate links are granted.
Also works fine on Huawei Honor 10.

**Comment by andrekir** [comment]
please read the docs: https://meshtastic.org/docs/software/android/android-usage#join-a-channel
