### ISSUE TITLE
1.3 release

### ISSUE THREAD

**Issue by joshbowyer** [meshtastic/Meshtastic-Android#432]
I flashed 1.3.10 to my node devices as 1.2 suffered from a serious GPS regression, but there is no Android app available that can communicate with it yet. When will the 1.3 version be released?

**Comment by andrekir** [comment]
there are a few pieces on the device side that need fixing before any client can work, as soon as the firmware is viable you can expect client releases.

**Comment by andrekir** [comment]
[Meshtastic Android 1.3.16 alpha preview](https://github.com/meshtastic/Meshtastic-Android/releases/tag/1.3.16)
