### ISSUE TITLE
No Channel Screen in 1.3

### ISSUE THREAD

**Issue by clavo2** [meshtastic/Meshtastic-Android#436]
The channel screen is often blank,  despite region being set....

Nothing can be edited.   Buttons do not work.  

![signal-2022-05-28-195122_001](https://user-images.githubusercontent.com/27170812/170849919-6b7c8975-a4de-4747-84ee-cc45144993c9.jpeg)

![signal-2022-05-28-195122_001](https://user-images.githubusercontent.com/27170812/170849929-b9beeb16-3016-4d99-bf9f-011f6dc2b2a2.jpeg)

**Comment by garthvh** [comment]
Are you running a 1.3 firmware?
