### ISSUE TITLE
Advanced Settings Don't Work - Unstable in 1.3

### ISSUE THREAD

**Issue by clavo2** [meshtastic/Meshtastic-Android#437]
Both 'Broadcast position (in seconds).    and     Deep sleep period (in seconds)

are sometimes settable, but don't hold their values.    If I were to set broadcast position to 375 and turn it on.  Leave the menu.    Come back,  It's set to turned off.  

Same for Deep sleep.    Randomly turns itself off.   

Sometimes one can be set and not another.   Regardless, The settings do not hold, and that makes me suspect if they are even being applied.

**Comment by andrekir** [comment]
@clavo2 appreciate you taking the time to test and report but android 1.3.11 is just a preview debug apk. until a release is made, it is expected to break.
