### ISSUE TITLE
Wifi AP support

### ISSUE THREAD

**Issue by ri0t** [meshtastic/Meshtastic-Android#455]
I have a T-Beam here that somehow has a garbled display output (i can always read one line, rest is random bits), so i can't really see the BLE pairing pin.

I tried setting the unit up as Access point, but there's no way to use it with a mobile phone as the web-client on it requires js from the intertubes and the android app doesn't connect to wifi devices.

**Comment by andrekir** [comment]
you can double press the middle button to set the Bluetooth pairing code to 123456 https://meshtastic.org/docs/software/device/#buttons

TCP/IP interface is available in the 1.3 app release.
