### ISSUE TITLE
Error: Code scanner module is not supported on current Google Play Services version, please upgrade

### ISSUE THREAD

**Issue by mc-hamster** [meshtastic/Meshtastic-Android#459]
I have 1.3.30 installed on an LG L322DL running Android 10 and when I try to scan a QR code, I get the error message:

"Code scanner module is not supported on current Google Play Services version, please upgrade"

I clicked the Report Bug button at 10:13pm PT.

Reproduced on another device, clicked Report Bug on that device at 10:40pm PT.

**Comment by Douile** [comment]
QR scanner doesn't work at all on phones without google play services, maybe its worth swapping to a different QR scanning library.

**Comment by andrekir** [comment]
@mc-hamster thanks for the report. fix is incoming.

@Douile thanks for mentioning aosp/microg. the app already uses zxing and handles channel url intents. play services code scanner is only meant for play store installs, so that needs fixing.

**Comment by Douile** [comment]
Oh mb i should have read the code instead of assuming. Sorry for off topic but is there a build flag or something i need to turn on to use zxing instead of play services?

**Comment by andrekir** [comment]
#461 should fix it. if you want to try the debug apk from that PR you can find it [here](https://github.com/meshtastic/Meshtastic-Android/actions/runs/2857532086).

**Comment by andrekir** [comment]
@mc-hamster when you have the time, please confirm if [1.3.38 release](https://github.com/meshtastic/Meshtastic-Android/releases/tag/1.3.38) fixes this issue for you.
