### ISSUE TITLE
Allow adding nodes via IP connection by manually providing an IP/host

### ISSUE THREAD

**Issue by Noki** [meshtastic/Meshtastic-Android#472]
In the latest 1.3 release the android application lists meshtastic nodes within the same network connected via WiFi. It would also be interesting to allow a connection to a remote node by providing an IP / host that is not within the same network / ip range.

**Comment by homesec24** [comment]
Oh yes, this would be very helpfull ... my nodes are also in a different network ... i can reach the web interface from any browser but not from the app.

**Comment by IZ1IVA** [comment]
I second that, it would be very useful!
