### ISSUE TITLE
Feature Request: Add New Device Settings to App

### ISSUE THREAD

**Issue by ghostop14** [meshtastic/Meshtastic-Android#492]
Some of the device settings such as imperial/metric units, fixed location versus GPS, and rotation would be nice to have accessible in the app.

**Comment by IZ1IVA** [comment]
> Some of the device settings such as imperial/metric units, fixed location versus GPS, and rotation would be nice to have accessible in the app.

I second that. Actually, I'd like to have all settings accessible through the app, as my remote nodes are more easily maintained by connecting to them with a phone than a computer.

**Comment by andrekir** [comment]
#520
