### ISSUE TITLE
show app version somewhere in the app

### ISSUE THREAD

**Issue by girtsf** [meshtastic/Meshtastic-Android#5]
I was running an older version of the app that I only found out when I went to the play store and saw an "update" button. Could we show the current app version under "Settings"?

**Comment by geeksville** [comment]
good idea.  It shows in the android settings for the app, but smart to also
put in the settings pane.

**Comment by lgoix** [comment]
I've began to work on the overflow menu to display an about screen and I am thinking to add a debug panel to display log (like raw comms received from device that could be copied)

**Comment by geeksville** [comment]
Omg that sounds great

(Sent from a phone - please ignore typos)
