### ISSUE TITLE
Occasional random notifications that app is disconnected on Android 12

### ISSUE THREAD

**Issue by Nestpebble** [meshtastic/Meshtastic-Android#504]
Latest beta app (1.3.45) installed on Android 12 smartphone. Occasionally, 1-3 times per day, a random notification will appear that says Meshtastic is disconnected. In the app, it is set to connect to none(disable).
Surely the notification is erroneous?

**Comment by PWRxPSYCHO** [comment]
Android 12, app version 1.3.45

pulled this info from the discord

**Comment by Nestpebble** [comment]
Here's some relevant screenshots:

![Meshtastic android notifications](https://user-images.githubusercontent.com/116762865/203377394-d6a36a39-b2f6-4335-9809-8a80e5e70a55.jpg)
![Screenshot_20221026_220423](https://user-images.githubusercontent.com/116762865/203378097-fb8bf10b-d02b-453c-91f7-cfae989cd40a.jpg)
