### ISSUE TITLE
Dialog color on Dark Mode isn't good.

### ISSUE THREAD

**Issue by Dtrieb** [meshtastic/Meshtastic-Android#506]
If you use the app on Dark Mode you can the the dialog box text not so good.

See Screenshot.
![Screenshot_20221029-125808](https://user-images.githubusercontent.com/3650284/198827713-960bb1e3-3575-4a4c-a075-2b598329ce40.png)

**Comment by thatSFguy** [comment]
I have the same issue, so based on the previous recommendation i switched to Default and force restarted the app.  In my case it seems to be related to Samsung devices as it worked fine with Moto phones.  I'm using a Samsung A42.    

Thanks!
