### ISSUE TITLE
Feature Request: Zoom Level of the Map

### ISSUE THREAD

**Issue by Dtrieb** [meshtastic/Meshtastic-Android#509]
Zoom more in the location, or select a zoom level at startup.

**Comment by PWRxPSYCHO** [comment]
@Dtrieb What version of the application are you on? Is the map still using MapBox or is it using OpenStreetMap?

Is the zoom for the nodes too far back? The current functionality is to fit all the nodes in on the screen at the same time. Also some map sources have a zoom in limit. ESRI can zoom to 22 while USGS can only go down to 15.

**Comment by Dtrieb** [comment]
@PWRxPSYCHO I use 2.0.0. (OpenStreetMap) and have this behavior if I the only node on the map.
