### ISSUE TITLE
Feature Request: Vibration on message arrived 

### ISSUE THREAD

**Issue by Dtrieb** [meshtastic/Meshtastic-Android#525]
It would be nice, if you can select a sound or vibration or both if a message arrived.

**Comment by hitachi8** [comment]
isnt that already possible? i tried on 3 different cellphones and mine all have a "Ding!" notification sound. i dont exactly remember vibration, but my guess would be that it is on the phone OS.

**Comment by andrekir** [comment]
this is handled via Android settings
