### ISSUE TITLE
shoud be renamed to "Meshtastic Background Service" and the channelId line above in a similar way "meshtastic_service" 

### ISSUE THREAD

**Issue by slavino** [meshtastic/Meshtastic-Android#54]
![Screenshot_20200616-082638_Settings](https://user-images.githubusercontent.com/1584034/84740700-22214f00-afae-11ea-9030-50307f305484.jpg)

https://github.com/meshtastic/Meshtastic-Android/blob/9a784b138597cff80249a57b0234ccdf3710596b/app/src/main/java/com/geeksville/mesh/service/MeshService.kt#L356

![Screenshot_20200616-082624_Settings](https://user-images.githubusercontent.com/1584034/84740739-32d1c500-afae-11ea-8bd2-f02f1f88ef01.jpg)

**Comment by slavino** [comment]
You may also consider putting human accessible value to strings.xml for later localization

**Comment by geeksville** [comment]
good find! will do on both counts!
