### ISSUE TITLE
T-echo wont display a temperature when its below 0°C

### ISSUE THREAD

**Issue by problex** [meshtastic/Meshtastic-Android#541]
Hi,
Having a problem where the T-echo wont display a temperature when its below 0°C in the Android app.
![image](https://user-images.githubusercontent.com/20313289/207640639-1f89953f-4725-40f0-bf52-6357cae14753.png)

Here are the serial logs.

02:49:57 4799 [Router] (Received from T-c): barometric_pressure=1033.558472, current=0.000000, gas_resistance=0.000000, relative_humidity=46.426758, temperature=-2.850000, voltage=0

As you can see it is receiving the temperature correctly with the negative symbol -2.850000

Link to Discourse [Discourse Link](https://meshtastic.discourse.group/t/eviromental-sensor-wont-report-temperatures-below-0-c/6871)

**Comment by Snowybirb** [comment]
Having the same issue on my RAK4631. Once temperature goes to a zero or negative number it won't display in the app but is showing up fine in the serial logs

**Comment by andrekir** [comment]
fixed in #532
