### ISSUE TITLE
message order

### ISSUE THREAD

**Issue by seydunatirej** [meshtastic/Meshtastic-Android#548]
When a message is sent repeatedly, the cloud shows as not received even though the message has reached the top. Aren't the messages in the queue one by one? I think they're all included at once

**Comment by andrekir** [comment]
not an app issue. grab device logs to see what is going on (likely a `MAX_RETRANSMISSION` error). also a crossed cloud doesn't mean not received.

**Comment by seydunatirej** [comment]
where exactly can i look

**Comment by andrekir** [comment]
for device logs use any serial monitor program while connected to USB, or if you have the python CLI installed run `meshtastic --noproto`

if you need help check https://meshtastic.discourse.group or Discord https://discord.gg/TYHeJpPc

**Comment by seydunatirej** [comment]
Thank you very much!
