### ISSUE TITLE
warn user if location services are turned off - explains many bluetooth problems

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-Android#55]
> well - thank you because you taught us of a bug that I bet explains **many** of the BLE connection problem complaints.  Tonight I'll add a warning if you have location services turned off.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/alpha-tester-thread-no-new-tests-needed-please-upgrade-to-release-version/298/60

**Comment by lgoix** [comment]
The phone needs the location to provides the GPS information. 

The device provide it when it is not paired to the phone ?

**Comment by geeksville** [comment]
@lgoix the app only needs that info if the device says it doesn't have a GPS.  If the device has a GPS we don't bother starting the location reading (to save CPU/power on the phone)

**Comment by geeksville** [comment]
(and we already had a warning in that case - but only in that case)

**Comment by lgoix** [comment]
I will investigate this, yesterday I was debugging for the battery level and wondered why it was using my phone location, there is a GPS, maybe sometime it says it doesn't
