### ISSUE TITLE
Feature Request: Add position history to the map view

### ISSUE THREAD

**Issue by pmarches** [meshtastic/Meshtastic-Android#550]
Seeing a history of the last few positions for each node would be very nice. Having a few history points allows you to estimate heading and speed.

**Comment by somnium78** [comment]
+1

i was just about to write a similar request. can the app use T-Beams rage test csv to show the last 10 or 20 positions?

**Comment by ryanjjennings** [comment]
This would be a nice feature.  Maybe pick last x minutes of history to show?

**Comment by mchuzie** [comment]
Absolutely. This would be a fantastic feature.

**Comment by LO77ARO** [comment]
+1   this would be nice!

**Comment by niksimms** [comment]
if this can trace for the last 10 entries that would be a good indication where it is going.

**Comment by HikerScott** [comment]
Last 5-10 positions, or even hour, is waaay too short for my use case.

Preferably each node could be assigned a colour and the full pin and label would only be shown on the latest entry.  All other "breadcrumbs" would just be visible squares in the color of the node.

Ideally we'd be able to track 48 hours or more of breadcrumbs and have a button to clear the map of breadcrumbs.  If it was "X number of positions" with a configurable number I would want the max number to be very very large.
