### ISSUE TITLE
docs: add info on how to reset Export rangetest.csv

### ISSUE THREAD

**Issue by edmkng** [meshtastic/Meshtastic-Android#561]
On a Heltec, even after wiping and restalling the firmware, the rangetest.csv still lives on the device. 

I.e. there's no way to reset the CSV file.
![Screenshot_20230112_092442_Meshtastic](https://user-images.githubusercontent.com/121360451/212092913-53e01a92-765f-461a-9f6e-ae6e67152a86.jpg)

I haven't tested this on the Tbeam.

**Comment by andrekir** [comment]
if you're using the "Export rangetest.csv" feature, to reset the values go to the Debug Panel and press the "clear" button.

I'll make a note to add this to [the docs](https://meshtastic.org/docs/software/android/usage#export-rangetestcsv).
