### ISSUE TITLE
Range Test Config > Save .CSV in storage - this function isn't consistent

### ISSUE THREAD

**Issue by edmkng** [meshtastic/Meshtastic-Android#563]
*** Background ***
I recently added another Tbeam to my existing collection of 2 Heltec V3 and another Tbeam.  (total of 2x Tbeam ; and 2x Heltec V3). I use 1 of the Heltecs as the base-station with 'Save .CSV in storage' enabled.  One Tbeam is attached to my dog and the tbeam broadcasts GPS every 30sec.   With this setup, I don't always  get GPS info recorded on the Rangetest.csv.    Sometimes, I enable the Range Test option and set 'Sender message interval' to 300sec.  This works better as it seems the first Range Test message was recorded and then subsequent msgs were also recorded.

*** The Issue ****
Now, with the second Tbeam... which was just been added a day ago, as soon as I flash it with the 2.0.10beta using the Web Flasher, I found out later that the new Tbeam has also been recording on the Rangetest.CSV eventhough the 'Save .CSV in storage' option is not enabled in the app.

I wiped and flashed again, the new Tbeam continues to record to Rangetest.CSV.  I used the App to Enable Range Test and Enable Save to .CSV.  Let it reboot.  Then I dis-enabled Range TEst and dis-enabled Save to .CSV.  Rebooted.  It's still recording to Rangetest.CSV.

**Comment by andrekir** [comment]
the app's [feature is similar but independent from the device range test module, and results may differ](https://meshtastic.org/docs/software/android/usage#export-rangetestcsv).
