### ISSUE TITLE
Subzero temperatures are not visible

### ISSUE THREAD

**Issue by Masterjagarn** [meshtastic/Meshtastic-Android#574]
When receiving telemetry data from BME280 sensor, the temperature reading does not show at all in the app if the temperature is below 0 degrees Celsius. The humidity and pressure values are thus shown correctly in the app. The temperature is shown correctly on the oled display on the meshtastic device.

**Comment by caveman99** [comment]
duplicate of #541 and fixed with app release 2.0.7. Please update your app.
