### ISSUE TITLE
Unable to define Bluetooth Fixed PIN (keyboard disappears)

### ISSUE THREAD

**Issue by mchuzie** [meshtastic/Meshtastic-Android#582]
Android v.2.0.14 > Device Settings > Bluetooth Config

Pairing mode FIXED_PIN
Tapped Fixed PIN cell, keyboard populates for a brief moment and disappears.
Unable to define Fixed PIN beyond default 123456

Galaxy S20 on Android 13

**Comment by andrekir** [comment]
https://issuetracker.google.com/issues/192043120

tested on Compose 1.4.0 and still not fixed. workaround is to click on any TextField to open the keyboard then scroll down.

**Comment by andrekir** [comment]
fixed https://github.com/meshtastic/Meshtastic-Android/commit/f66a3fabc7ae339f55278cb91920b513ad84b29b
