### ISSUE TITLE
allow copying the gps coordinates of the peers

### ISSUE THREAD

**Issue by krasi-georgiev** [meshtastic/Meshtastic-Android#592]
on the map when clicking a peer it shows its distance and GPS coordinates, but to be able to navigate to it need to also copy the coordinates and use these in google maps for navigation.

so long press-to-copy feature would be a great addition.

**Comment by RightHandMan1** [comment]
In the peers tab(click the people), it shows they're position as a link. Clicking that link, will let you open it in maps,etc.

**Comment by krasi-georgiev** [comment]
Thanks I just tried it, and it does open google maps but doesn't populate the coordinates in the search box of maps
