### ISSUE TITLE
App-wide: Numerical Fields need units added to label

### ISSUE THREAD

**Issue by User12005** [meshtastic/Meshtastic-Android#596]
Most numerical data fields throughout the app populate with values, and it's not clear what the units are.

Meters or feet?

Minutes or seconds?

This can be improved by just adding the units in parentheses to the label for the data field. 

Example:

'GPS Update Interval (sec)'

'Altitude (m)'

'rssi (dBm):'

**Comment by rudydevolder** [comment]
That's true. Now I also get mixed up with 'm' for meters and the same 'm' for minutes. Really enoying and confusing
