### ISSUE TITLE
Please update F-Droid

### ISSUE THREAD

**Issue by SR7673** [meshtastic/Meshtastic-Android#600]
The latest beta version 2.0.22 is not available on the f-droid app, so people using that app can't update...

**Comment by SR7673** [comment]
Hmm, strange. The latest version shown here is 2.0.19. Until now the app always suggested new versions (i didn't need to update the app (f-droid) manually)...

**Comment by andrekir** [comment]
we are moving to F-Droid's mainline repository. while we wait for inclusion, follow: https://meshtastic.org/docs/software/android/installation#install-with-f-droid

note that F-Droid releases are now completely different, so switching can fail to update and may require to uninstall/reinstall the app.
