### ISSUE TITLE
[UI BUG] Can not set region Pixel 4a

### ISSUE THREAD

**Issue by ramaboo** [meshtastic/Meshtastic-Android#601]
On a Pixel 4a you can't set a region. 

See these screenshot. No matter where you click on the select drop down it won't set the region. It just stays unset.

![Screenshot_20230309-120056](https://user-images.githubusercontent.com/84117/224141465-c664aab5-a308-47a6-989d-82945d1305b3.png)
![Screenshot_20230309-120038](https://user-images.githubusercontent.com/84117/224141479-f8481c3d-945c-4099-9e0d-90ee91874261.png)

**Comment by andrekir** [comment]
what device and firmware version?

**Comment by ramaboo** [comment]
Pixel 4a Android 13. Mestastic android app 2.0.22.

**Comment by andrekir** [comment]
device can be Tbeam/RAK/etc and the Meshtastic software version it is running.

**Comment by andrekir** [comment]
apps can't communicate with devices running old firmware. looks like this is your issue. try flashing the latest 2.1.x: https://meshtastic.org/docs/getting-started/flashing-firmware 

if that doesn't work let me know.
