### ISSUE TITLE
[Feature Request] Add Hoplimit information to the node view

### ISSUE THREAD

**Issue by Andrey-VD** [meshtastic/Meshtastic-Android#611]
Currently, using the meshtastic --info command, you can get information about the Hoplimit of the node and about the Hoplimit of the received message.
_For example 
'lastReceived': {'from': 2229140548, 'to': 4294967295, 'id': 104504839, 'rxTime': 1680164763, 'rxSnr': 6.25, **'hopLimit': 7**, rxRssi': -57, 'fromId': '!84ddfc44', 'toId': '^all'}, **'hopLimit': 7**}
_
The nodelist contains rssi, the value of which is taken from the same source.

It would be very useful to see the values about the HL values in the node list, , в формате  7/7

**Comment by andrekir** [comment]
we don't have every nodes hop_limit. more info: https://github.com/meshtastic/firmware/issues/2003
