### ISSUE TITLE
App 2.1.6 crashes when tapping the + button

### ISSUE THREAD

**Issue by IZ1IVA** [meshtastic/Meshtastic-Android#614]
Android 11
Pixel 4a
App 2.1.6

After tapping the + button in the nodes list, the app crashes. Did not happen with 2.1.5 and previous versions.

Cheers

**Comment by andrekir** [comment]
fixed in [2.1.7](https://github.com/meshtastic/Meshtastic-Android/releases/tag/2.1.7)
