### ISSUE TITLE
Buttons illegible in dark mode

### ISSUE THREAD

**Issue by jaykayenn** [meshtastic/Meshtastic-Android#616]
In dark mode, white text on green buttons are illegible. 

Ver: FDroid-2.1.4
Device: Sony Xperia 5ii, Android 11

**Comment by daviscodesbugs** [comment]
Agreed; there are a couple of places where certain labels aren't very legible 

![image](https://github.com/meshtastic/Meshtastic-Android/assets/22112533/3fb21d32-d890-4479-9867-071e3dc6bf03)

I'll try and take a look at this soon

**Comment by daviscodesbugs** [comment]
@andrekir I'll tackle this next after #870 is merged. Can I be assigned this and #817 ?

**Comment by andrekir** [comment]
> @andrekir I'll tackle this next after #870 is merged. Can I be assigned this and #817 ?

for sure. done!
