### ISSUE TITLE
[Bug]:  Android app vs 2.1.4 , peers show distance in km instead of miles

### ISSUE THREAD

**Issue by RightHandMan1** [meshtastic/Meshtastic-Android#621]
Version 2.1.4 of the android, (2.1.17 firmware), in device settings I have Imperial selected, but the peers list keeps showing their distance in km. this node IS connected to wifi and mqtt, but assume it should still translate the distance.

**Comment by caveman99** [comment]
device settings only alter the on-display appearance for the device, not the representation in the app. I think the app gets the unit settings from the phone locale.

**Comment by RightHandMan1** [comment]
seems not, the phone is set to all-merican , still show peers in km, node display shows in miles properly. Still this way in ver 2.1.10

**Comment by RightHandMan1** [comment]
Still this way in 2.1.14 android app. Since the app can change the node, read the node, it should follow the node settings.
