### ISSUE TITLE
Bug: 2.1.8 crashes on first installation

### ISSUE THREAD

**Issue by mverch67** [meshtastic/Meshtastic-Android#622]
When installing 2.1.8 for the very first time (i.e. on a phone where meshtastic never ran before) the APP crashes immediately after start.

Same happens when removing all existing Data and deinstall the APP, then reinstall.

**Comment by karamo** [comment]
**My workaround:**
• uninstall APP 2.1.8
• install APP 2.1.3 > start > test > ok
• install APP 2.1.8 without deinstall 2.1.3 > start > ok > message > ok

**Comment by andrekir** [comment]
this is fixed, will be out in the next release.
