### ISSUE TITLE
[Feature Request]: Android app BT auto reconnect 

### ISSUE THREAD

**Issue by PhilipLykov** [meshtastic/Meshtastic-Android#637]
### Platform

NRF52, ESP32

### Description

After you leave a BT range of your Meshtastic device it becomes disconnected and to connect it back you need to open the app, disconnect and reconnect to your device. It's very inconvenient. Will be great to make the app to search for last used device and reconnect automatically every minute.

**Comment by andrekir** [comment]
app already does reconnect whenever Bluetooth is in range. something is wrong with your setup.

**Comment by PhilipLykov** [comment]
> app already does reconnect whenever Bluetooth is in range. something is wrong with your setup.

So let's call it like this: on 3 different devices on MIUI 14 and MIUI 13 it doesn't reconnect automatically. And have to be reconnected manually. I gave all possible permissions in the MIUI to Meshtastic app and switched off the battery saver for it.
