### ISSUE TITLE
[Feature Request]: Respect Portrait Screen Rotation

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic-Android#640]
I have a tablet that's mounted on my wall upside down (due to charging port location) and unfortunately except for the initial welcome message, the Meshtastic app does not respect my screen's orientation and displays only in Portrait which is upside down for me. 

I experimented and rebuilt the app changing the below line to `android:screenOrientation="sensorPortrait"` which seems to resolve the issue on my tablet while also not creating any new issues on my P7P. Would this be an appropriate change?  

https://github.com/meshtastic/Meshtastic-Android/blob/72f02b0deb67cd2016a49fecaafd6b94b1846baf/app/src/main/AndroidManifest.xml#LL132C40-L132C40

**Comment by andrekir** [comment]
LGTM
