### ISSUE TITLE
[Feature request]: Add "turn on location" Bluetooth message

### ISSUE THREAD

**Issue by ajmcquilkin** [meshtastic/Meshtastic-Android#648]
Add an informational message telling users that they may need to turn on their phone's location to be able to connect to Bluetooth devices. I've heard that this may be related either to Android version or to phone hardware model, but to be safe I'd push for including the message for all users. I would be looking for something to the effect of "If you don't see any devices, try turning location on."

**Comment by andrekir** [comment]
this is no longer an issue
