### ISSUE TITLE
[FEATURE] Custom connection options

### ISSUE THREAD

**Issue by tb0hdan** [meshtastic/Meshtastic-Android#649]
Hi,

Please add the following:

- Custom IP:Port for Meshtastic devices behind router (and possibly HTTP basic or similar)
- Keepalive / Timeout / Reconnect options for WiFi + request above

Much appreciated.

**Comment by ut3uku** [comment]
I consider it's important!

**Comment by G2Dolphin** [comment]
Yeah, I already [https://github.com/meshtastic/Meshtastic-Android/issues/643](posted) similar FR, which is similar to [https://github.com/meshtastic/Meshtastic-Android/issues/472](other FR) before.

**Comment by jp-bennett** [comment]
It doesn't sound like a good idea to expose a Meshtastic device to the Internet, even on a random port. A VPN like Wireguard is a much better approach. PR #663 does allow that use case.
