### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by jp-bennett** [meshtastic/Meshtastic-Android#652]
Android Studio can't find usb-serial-for-android:3.4.6. I've had to change that line to

`implementation 'com.github.mik3y:usb-serial-for-android:v3.4.6'`

at https://github.com/meshtastic/Meshtastic-Android/blob/05327d2c05bd40662c130b6caa61c1f09bcef7e4/app/build.gradle#L219

Not sure if this is just a problem on my machines. But it was required to compile successfully. 

Error was:

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileFdroidDebugAidl'.
> Could not resolve all files for configuration ':app:fdroidDebugCompileClasspath'.
   > Failed to transform usb-serial-for-android-3.4.6.aar (com.github.mik3y:usb-serial-for-android:3.4.6) to match attributes {artifactType=android-aidl, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find usb-serial-for-android-3.4.6.aar (com.github.mik3y:usb-serial-for-android:3.4.6).
        Searched in the following locations:
            https://jitpack.io/com/github/mik3y/usb-serial-for-android/3.4.6/usb-serial-for-android-3.4.6.aar
            https://jitpack.io/com/github/mik3y/usb-serial-for-android/3.4.6/usb-serial-for-android-3.4.6.jar

**Comment by andrekir** [comment]
every code changes trigger CI builds using GitHub Actions, so we know when anything breaks https://github.com/meshtastic/Meshtastic-Android/actions

thats what the "checkmark" in front of commits represent (build success/failure). so definitely no build issues in the code.

you can also enable GitHub Actions on your fork's Settings.

**Comment by jp-bennett** [comment]
It would be useful to understand this particular problem, to add a step to the build instructions. I've replicated this on two different machines, a Fedora and a Pop_OS machine.

**Comment by andrekir** [comment]
odd. the standard format for library versions in Gradle has no prefix and the [lib repo](https://github.com/mik3y/usb-serial-for-android#quick-start) doesn't suggest that notation. you can see task ':app:compileFdroidDebugAidl' passed the latest [CI running Ubuntu 22.04.2 LTS](https://github.com/meshtastic/Meshtastic-Android/actions/runs/5479463850/jobs/9981520604#step:7:17).

**Comment by andrekir** [comment]
closing. if anyone else is having issues please comment below.
