### ISSUE TITLE
[Feature Request]: In-App Basic Resources/Help/Tutorials

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic-Android#676]
I would like to suggest incorporating resources within the app to help new users.  Basically a section within the app that provides basic help guides, and/or tutorials. Things that can be easily be shown visually in the app, outside of just linking to the docs. This could include:

1. Getting Started Guide: A simple walkthrough for first-time users on how to set up and use the app and devices. Similar to what's currently shown on first-start but updated and with more info.
2. FAQs: A list of frequently asked questions and their answers to help users troubleshoot common issues when using the android app.
3. Tutorials: Step-by-step guides on how to use common features of the app. Essentially little slide shows for a given topic to help a user see visually.

What I'm envisioning are basic items specifically related to using the app, not configuring the devices (for this we can still refer to the docs). So an example "Adding a channel: Press on the channel tab, press the pencil, press the +" etc etc. But visually.

**Comment by andrekir** [comment]
in-app documentation is very rare because it's very high-maintenance. not sure this is the way to go.

updating/improving the existing onboarding is the low hanging fruit. we can show static images with title (top) and text (bottom).

for a better visual experience I'd suggest short on-topic youtube videos for each basic item/task/FAQ.

**Comment by Coehill** [comment]
I think tool tips when tapping on setting names would be a useful compromise.

**Comment by Coehill** [comment]
> in-app documentation is very rare because it's very high-maintenance. not sure this is the way to go.
> 
> updating/improving the existing onboarding is the low hanging fruit. we can show static images with title (top) and text (bottom).
> 
> for a better visual experience I'd suggest short on-topic youtube videos for each basic item/task/FAQ.

Agreed. Or even better, use PeerTube which is distributed, decentralized video hosting using P2P. Essentially, the mesh of video sharing.
