### ISSUE TITLE
[Bug:] 2.2 LoRa Config Menu not loading

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic-Android#677]
Myself and another user are noticing the LoRa config menu will not correctly load for both the connected and a remote node. The screen is black. Other menus are loading fine. 

For me it's a 2.2 device with 2.2 app, for the other user it was both 2.2 and 2.1.23 device and 2.2 app. 

https://github.com/meshtastic/Meshtastic-Android/assets/6912600/3762bb9e-9847-49b2-b0cc-76aefc48fd3d

<img width="680" alt="Screenshot 2023-08-09 at 5 34 12 PM" src="https://github.com/meshtastic/Meshtastic-Android/assets/6912600/c26c1fbb-d65d-402c-8454-c5e508fa1c1f">

**Comment by andrekir** [comment]
fix will be in the next release https://github.com/meshtastic/Meshtastic-Android/commit/16323d7d53be3e5f8232a862ed65ccbc15d1f6a8
