### ISSUE TITLE
[Feature request] Change UI logic for  connecting to device by IP

### ISSUE THREAD

**Issue by mrekin** [meshtastic/Meshtastic-Android#691]
Now I have some not very usefull behavior when interracting with node, connected by wifi\ip.
In my case node has static IP inside my home network, so I use the same ip address every time.

1. Provided IP drops from app time by time, app don't save it and I have to enter it again
2. Menu item "IP address" not enabled even ip address field is filled in - I have to edit field to make menu item selectable.

**Comment by frazzmatazz** [comment]
I second this suggestion. And was pointed here while discussing it on discord.

The android app forgets the IP address regularly (I think whenever I connect to something by BT). And after you reenter it, you have to click the greyed out "IP Address" above again to make it connect.
Here's my video of the slightly unintuitive process of adding a node by IP address.  
https://discord.com/channels/867578229534359593/871539863307055134/1225230295272521730
