### ISSUE TITLE
Feature: Resend Button

### ISSUE THREAD

**Issue by tuxphone** [meshtastic/Meshtastic-Android#73]
Right now if your message is lost or not confirmed - you have to type it again. No copy and paste in the message box or another way for easy resending of your message.

So i would like to have an option to show the last message(s) and resend them via Enter.
Perhaps an "Up Arrow" icon at the right side of the text box? Pressing it would show the last line or perhaps even older (own) messages.

**Comment by geeksville** [comment]
good idea.

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/copy-paste-function-of-a-message-send-but-failed/922/4

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/1-2-31-feedback/3370/1
