### ISSUE TITLE
Meshtastic as mock location app

### ISSUE THREAD

**Issue by artiommocrenco** [meshtastic/Meshtastic-Android#732]
It would be great if meshtastic could serve as mock location app (an existing developer option) to Android.

Use case scenario is getting location in openstreetmaps and other location-aware apps, where meshtastic would serve as location provider.

Meshtastic devices can have superior GPS reception capabilities than phones.

**Comment by andrekir** [comment]
Android developer options like mock locations are intended for testing and debugging purposes and are not meant for use in production.

if users have a genuine need for mock locations they can do so by creating a separate application or integration that consumes Meshtastic data using our [public API](https://github.com/meshtastic/Meshtastic-Android/blob/a250555ee5fd86c9471764474c1dfa3954080a97/app/src/main/aidl/com/geeksville/mesh/IMeshService.aidl#L12).
