### ISSUE TITLE
Range Test doesnt work when using a board that doesnt have on-board GPS.

### ISSUE THREAD

**Issue by hitachi8** [meshtastic/Meshtastic-Android#752]
hello.

sadly i have found out that when doing a range test with the included code. all the data is saved and everything seems alright until after my trip i found out that the saved position were of the last time i was connected to my wifi network. i think the issue is that even thought i am normally using the cellphone GPS to provide location, it seems the Range Test code doesnt make use of it and instead expect to use the on-board GPS.

**RangeTest using a LoRa board without a on-board GPS doesnt log the coord correctly**

the Code would need to somehow use the phone GPS (if possible) to provide the GPS coord instead of relying solely on the on-board GPS that is sometimes not available to use on certain plateform.

**Comment by andrekir** [comment]
the source for position data makes no difference (onboard or phone GPS). what you are seeing is due to this bug: meshtastic/firmware#2826

should work fine once it is fixed.
