### ISSUE TITLE
Better input for message In the "add quick chat message"

### ISSUE THREAD

**Issue by noffeperfekt** [meshtastic/Meshtastic-Android#783]
Currently, the input for the quick message is a single line of text (android:inputType="textShortMessage") this does not correlate with the type of input that is used when writing a message (android:inputType="textMultiLine|textCapSentences") whitch is multiline-capable.

**Problem**:
With textShortMessage you can only have single line quick message.

**Solution**: 
Change `android:inputType="textShortMessage"` to `android:inputType="textMultiLine|textCapSentences"` on line 17 in file `app/src/main/res/layout/dialog_add_quick_chat.xml`

Did not find any contribution info, do you want me to do a pull request?

**Comment by andrekir** [comment]
good catch. you may also cap it to 228 maxLength to match messageInputText. 👍
