### ISSUE TITLE
Android App Unresponsive When MQTT Enabled

### ISSUE THREAD

**Issue by jyunte** [meshtastic/Meshtastic-Android#799]
This affects versions from the current Beta 2.2.15.3 to the current Alpha 2.2.16.1 on the Heltec 915MHz LoRa ESP32 OLED Board V3:

Meshtastic app works fine from node to node over RF. Messages are sent through and received in both directions using default Meshtastic settings (only User name and Region changed).

When one node has MQTT enabled, the communication between the hardware and app ceases as far as viewing and changing settings is concerned.

To reproduce from a working simple node:
1. Click the "..." icon at the top right of the screen.
2. Click Radio configuration.
3. Click MQTT
4. Click MQTT Enabled to turn MQTT on.
5. Click Proxy to client enabled to turn it on.
6. Click the Back button
7. Click Channels.
8. Click LongFast.
9. Click Uplink Enabled to turn it on.
10. Click Downlink Enabled to turn it on.
11. Click Save.
12. Click Send.

![Screenshot_20231217_123307_Meshtastic](https://github.com/meshtastic/Meshtastic-Android/assets/56657512/b0b5d19d-d896-4919-999d-2683aec7894b)

![Screenshot_20231217_123251_Meshtastic](https://github.com/meshtastic/Meshtastic-Android/assets/56657512/785cf504-6d70-4f32-9c79-952e41a88443)

The module begins receiving data from the mesh network. Incoming messages appear on the module's screen, and then many minutes (hours?) later appear on the app. Messages sent from another device on the local mesh appear to upload to the MQTT node module, but do not appear to make it out to the wider network.

After a few minutes, it becomes impossible to use the app to read or change any settings. The app's interface responds, but no data is transferred between the module or the app. The progress bar remains at 0%

![Screenshot_20231217_203540_Meshtastic](https://github.com/meshtastic/Meshtastic-Android/assets/56657512/31dc1a0b-f57f-4aae-bdd1-66c1414725c7)

The only way to change a setting is to rewrite the firmware. Unplugging the module for several hours does not help, so it does not appear to be a thermal issue.

I've tried the same procedure on two Heltec 915MHz LoRa ESP32 OLED V3 boards with identical results.

**Comment by andrekir** [comment]
radio is unresponsive, not the app

reference https://meshtastic.discourse.group/t/esp32-oled-board-v3-boards-unresponsive-in-android-app/8815
