### ISSUE TITLE
Star close contact 

### ISSUE THREAD

**Issue by johnnytshi** [meshtastic/Meshtastic-Android#801]
Hello everyone,

I recently began exploring Meshtastic and activated MQTT. However, I find the user interface quite loaded (list of nodes). Is there an option to highlight or bookmark specific nodes for easier access?

Best regards.

**Comment by Ferretdog** [comment]
This is especially true if you are using with mqtt - your node list will end up full and your own nodes and friends will be lost in the noise.

**Comment by Coehill** [comment]
Perhaps this should be a separate issue but being able to add an alias to a node will hemp with identifying your friends of you can't remember everybody's callsign.

**Comment by andrekir** [comment]
done in #920
