### ISSUE TITLE
[Feature Request] Ability to copy a node's GPS coordinates from node list

### ISSUE THREAD

**Issue by Nestpebble** [meshtastic/Meshtastic-Android#805]
I'd like to be able to long press the GPS coordinates in the nodes list and copy it, rather than just a link to my mapping app.

**Comment by Ferretdog** [comment]
This is a good idea. In addition, a hook into the sharing or open-in dialogue so you can open the location in a different mapping app, share it direct to another app, or copy it for pasting.
