### ISSUE TITLE
Some locale settings cause an incorrect CSV file

### ISSUE THREAD

**Issue by lukipuki** [meshtastic/Meshtastic-Android#818]
In certain languages, the [decimal separator is a comma](https://en.wikipedia.org/wiki/Decimal_separator#Examples_of_use), causing the `rangetest.csv` exported by the app to be incorrect, as the column separator is also a comma. The SNR data then actually spans two columns, as a number such as "4.25" is split into two columns "4" and "25".

This line of code
https://github.com/meshtastic/Meshtastic-Android/blob/5d96bd6838440ca39bb058dcf7365b7c21c3c5d0/app/src/main/java/com/geeksville/mesh/model/UIState.kt#L496
should be probably changed to `val rxSnr = "%f".format(Locale.ENGLISH, proto.rxSnr)`. Other fixes are possible too.

I happen to have Android Studio installed but I didn't manage to get the app built, so I'm unable to provide a PR at this point. I might try later, though.

**Comment by andrekir** [comment]
good catch. we can change the CSV delimiter to avoid locale conflicts. will be fixed in the next release.
