### ISSUE TITLE
App only shows LoRa Frequency

### ISSUE THREAD

**Issue by radiodiscone** [meshtastic/Meshtastic-Android#820]
Hello,

The android version of the app only shows the current LoRa frequency, not the channel number, like the webUI, iOS app, and meshtastic CLI only show channel number. It would be helpful if this was also displayed if the current frequency corresponds to a channel, but I would keep the ability for the frequency to be set manually outside of predefined channels.

**Comment by andrekir** [comment]
![Screenshot_20240121_155130_Meshtastic](https://github.com/meshtastic/Meshtastic-Android/assets/48680741/4fbf2720-b0ae-494a-8ea4-ba1973d3b30d)
