### ISSUE TITLE
Display temperature in Fahrenheit in the app

### ISSUE THREAD

**Issue by N1obu** [meshtastic/Meshtastic-Android#845]
It would be nice if the Android app could display the temperature in Fahrenheit.

![20240210_155327](https://github.com/meshtastic/Meshtastic-Android/assets/100533255/6334d374-2a0c-4859-9312-89776547d4cb)
![20240210_155405](https://github.com/meshtastic/Meshtastic-Android/assets/100533255/719056b5-9e0b-4af3-8d7d-4d6d07d7c733)
![Screenshot_20240210_155419_Meshtastic](https://github.com/meshtastic/Meshtastic-Android/assets/100533255/58f7e6b5-2fbb-4e62-afde-5ef394f3c1bc)

Reference an Open & Closed issue #3180 on the Meshtastic github.

T-Beam is configured and displays Fahrenheit but the Android app continues to display Celsius.

**Comment by andrekir** [comment]
![Screenshot_20240212-191626](https://github.com/meshtastic/Meshtastic-Android/assets/48680741/8d711ffc-4c9a-45ad-8300-dff5d8b3aada)

Temperature unit is already in sync with `Radio Config > Telemetry > Environment metrics use Fahrenheit`

I can't reproduce this.
