### ISSUE TITLE
Deeplinking is broken

### ISSUE THREAD

**Issue by adriantache** [meshtastic/Meshtastic-Android#846]
Deeplinks, for example for joining a channel, are broken, and the links open in the browser instead. I have checked, and [the file](https://meshtastic.org/.well-known/assetlinks.json) does exist, but maybe the app signature has changed? If it's not that, and it's the new Android 14 explicit intents, maybe I can try to fix them myself and raise a PR.

**Comment by andrekir** [comment]
can you confirm your version and install source (Play Store, APK, F-Droid)?

**Comment by adriantache** [comment]
Installed from the Play Store, although it seems I was missing the latest update (and it keeps failing to install, for some reason, maybe my version was signed with a different key?).

**Comment by andrekir** [comment]
odd. the release build runs via GitHub actions. no changes there.

**Comment by andrekir** [comment]
updating from 2.2.19 to 2.2.20 seems to be the problem. I suspect this is the cause: https://github.com/meshtastic/Meshtastic-Android/commit/d75188f03c80614e33762212fa4df3b10eddc6a6

I'll revert that for the next release.
