### ISSUE TITLE
[Feature Request]: Role Descriptions

### ISSUE THREAD

**Issue by rcarteraz** [meshtastic/Meshtastic-Android#848]
I've been thinking about how we can make the Android app more user-friendly, especially for newcomers setting up their devices. My suggestion? Let's include descriptions for each role directly in the role selection menu, similar to what's already done in the Apple app. I know I know different ecosystems, different developers. I totally get that and normally don't push for parity but I think in this instance it could be very beneficial.

**Why This Matters:**
- **Instant Clarity:** Jumping out to the docs to understand roles can be a hassle. Even if you read them beforehand, you still have to remember which is which and match the definitions in your mind which isn't easy. Having descriptions on-hand makes the setup process smoother and keeps the user focused.
- **Informed Decisions:** I think with descriptions readily available, users (especially newer ones) are more likely to choose the role that truly fits their needs/use-case. Which probably is a win later on. 
- **Consistency Across Platforms:** Like I mentioned, while I normally don't press for this. I think in some instances this type of consistency across platforms can be extremely beneficial. Bringing this feature to Android aligns it with the Apple app, offering a cohesive experience to all users, regardless of their device.

**The Big Picture:**
This request is about enhancing the setup experience, and making it more intuitive and informative. It's a small change that could make a big difference in helping users understand the capabilities and best use cases for each role without having to leave the app.

Would love to hear your thoughts on this and whether it's something we can roll out.

**Reference Links:**
https://meshtastic.org/docs/configuration/radio/device/#roles
https://github.com/meshtastic/protobufs/blob/b9479e6c68e6042e7ff0b427cdedbac078556d86/meshtastic/config.proto#L19

**Comment by tropho23** [comment]
I think this is a great idea, and either a popup or some mechanism to show the role description would be excellent.

Is there some less-intrusive way to do this than an annoying in-your-face popup?
