### ISSUE TITLE
Remove firmware update logic and SoftwareUpdateService

### ISSUE THREAD

**Issue by daviscodesbugs** [meshtastic/Meshtastic-Android#853]
As mentioned in #850 
The firmware update logic and SoftwareUpdateService is outdated and unused. It can be refactored out
Remove the "Update Firmware" button on the settings page

**Comment by andrekir** [comment]
> Is the "Update Firmware" button on the settings page also okay to remove?

yes.

> Also, is there another mechanism for updating radio firmware from the app, or is it just no longer supported?

there is Bluetooth OTA support in the firmware but it was replaced in 2.0, so the app side will have to start from scratch.
