### ISSUE TITLE
[Feature Request]: Add toggle text to QR function.

### ISSUE THREAD

**Issue by btcpuertorico** [meshtastic/Meshtastic-Android#863]
To enable easier air gapped data transfer from Meshtastic client to other devices.

![Feature_Meshtastic](https://github.com/meshtastic/Meshtastic-Android/assets/63824372/31426cd9-ca61-4039-85d1-7e22c2786ec0)

**Comment by andrekir** [comment]
can you give more context on what you're trying to do here?

**Comment by andrekir** [comment]
unfortunately that's too much of a niche feature and no interest in implementing it at this time.

**Comment by btcpuertorico** [comment]
Just as ATAK? Niche, Jesus!
