### ISSUE TITLE
Canceling a new "ignore incoming" crashes the app

### ISSUE THREAD

**Issue by Mertszr02** [meshtastic/Meshtastic-Android#872]
Steps to replicate: 
1. 3 dot menu
2. Radio configuration
3.  Lora
4. Ignore incoming --> **[add]**
5. Write a 10 char long device id _(no weird behavior for 9 or shorter length)_
6. Hit **[X]** to cancel
This causes the app to crash and stops the background process ie. disconnects from the node and reconnects when the app is launched.

If you add the node by pressing **[add]** again then delete with **[X]** it all works as intended.

I have first encountered this behavior in 2.2.20, recently updated to 2.2.23 the bug is still there.
My device info: Xiaomi Mi9, MIUI 12.5.1, Android 11

**Comment by andrekir** [comment]
good catch. should be fixed in the next release.
