### ISSUE TITLE
Make use of precision_bits in location packets

### ISSUE THREAD

**Issue by jp-bennett** [meshtastic/Meshtastic-Android#893]
Incoming location packets can now contain the precision_bits field, which indicates how precise the location is. It would be nice to indicate on the map the imprecision, probably by drawing a shaded circle around the indicated position. Chart of what the values mean:
Precision bits setting of x results in a maximum offset (circle radius) in meters of Y

2 +/- 5976446.981252
3 +/- 2988223.4850600003
4 +/- 1494111.7369640006
5 +/- 747055.8629159998
6 +/- 373527.9258920002
7 +/- 186763.95738000044
8 +/- 93381.97312400135
9 +/- 46690.98099600022
10 +/- 23345.48493200123
11 +/- 11672.736900000944
12 +/- 5836.362884000802
13 +/- 2918.1758760007315
14 +/- 1459.0823719999053
15 +/- 729.5356200010741
16 +/- 364.7622440000765
17 +/- 182.37555600115968
18 +/- 91.1822120001193
19 +/- 45.58554000039009
20 +/- 22.787204001316468
21 +/- 11.388036000988677
22 +/- 5.688452000824781
23 +/- 2.8386600007428338
24 +/- 1.413763999910884

**Comment by garthvh** [comment]
Adding your link here https://github.com/osmdroid/osmdroid/issues/831

Looks like Polyline.pointsAsCircle(center, radius) is the ticket

on iOS I used a function to return the appropriate circle radius based on the integer
