### ISSUE TITLE
Feature Request: Node colours and chat bubbles

### ISSUE THREAD

**Issue by b8b8** [meshtastic/Meshtastic-Android#899]
Please look at making the algorithmically defined node colour in the node list also match the name-bubble colour in the public and private channels to make it a little easier to sort through the conversations. Excuse my "advanced" photoshop skills.
![signal-2024-03-06-173540_002](https://github.com/meshtastic/Meshtastic-Android/assets/156552149/bf265213-4b57-4a1f-aa63-4f307fb5f979)

**Comment by andrekir** [comment]
completed in https://github.com/meshtastic/Meshtastic-Android/commit/4a1319a645a20ec2156f113d6923b8d6cd8e8447

**Comment by b8b8** [comment]
Thank you so much for coming back to this change.
