### ISSUE TITLE
Feature Request: Ability to Bulk Delete (Not Ignore) Known Nodes

### ISSUE THREAD

**Issue by djripcord** [meshtastic/Meshtastic-Android#903]
As mentioned, it would be very handy to be able to delete known nodes in the app. As Meshtastic becomes more popular, more nodes will be found and they will begin to clog up the node list. I experienced this today when MQTT came online and I suddenly had 50 nodes in my list. Frustrating that I couldn't hide or delete them. Because even if I chose to ignore the node, it was still present, just with a strike through the name.

**Comment by Pscope** [comment]
What about an option to hide or delete the node list after X hours/days that way the list is kept automatically relevant to recently seen nodes. with the possible option to tag nodes you want to stay sticky and never vanish?

**Comment by andrekir** [comment]
you can already reset the node database in `Radio Configuration > nodeDB reset`.
