### ISSUE TITLE
QR Code displayed while in Managed Mode

### ISSUE THREAD

**Issue by ctrose010** [meshtastic/Meshtastic-Android#904]
Hello!
In discussion with others in the Discord channel, we came across a bug within the Android app. 
If a node is in managed mode, the android client is still able to get the QR code, which includes the PSK to the admin channel. This creates a security risk where a user would be able to use the CLI and disable managed mode, when they would not be supposed to.

Overall: The QR Code screen should be disabled when the node is in Managed Mode.

**Comment by andrekir** [comment]
managed mode isn't really a security feature, it's just a client convenience to avoid accidental changes by family and friends.

it is only implemented in the Android and Apple apps. the python CLI is left out by design, and you don't need the QR code to make any changes.
