### ISSUE TITLE
No GPS Enable option on 2.3 Android

### ISSUE THREAD

**Issue by slash-bit** [meshtastic/Meshtastic-Android#911]
If GPS Mode was previously set to DISABLE and then to ENABLE, GPS still doesn't function.
Reason 
![Screenshot_20240313-231028_Meshtastic](https://github.com/meshtastic/Meshtastic-Android/assets/77391720/c8822b8d-9435-4ce9-a5bc-21e603461ea5)
is that there is no GPS Enable slide button available on Android App 2.3 to enable the GPS.
This slide button exist in the Web App and seems the only way to enable GPS.
<img width="682" alt="image" src="https://github.com/meshtastic/Meshtastic-Android/assets/77391720/94d4d967-8004-402e-abd4-95b04a953a80">

**Comment by garthvh** [comment]
The toggle is not used by 2.3 firmware, just the drop down, you have to have an older version to use the toggle.

**Comment by andrekir** [comment]
the `gps_enabled` boolean was deprecated in 2.2.21 in favor of the Triple state GPS mode: https://github.com/meshtastic/protobufs/pull/428 & https://github.com/meshtastic/firmware/pull/3157.
