### ISSUE TITLE
Android notification on new node i db

### ISSUE THREAD

**Issue by Ztrby** [meshtastic/Meshtastic-Android#914]
Feature request

Option to have the app make a notification in Android notification when new node is found in the mesh and added to the database. 
Should maybe be disabled as default

**Comment by Kealper** [comment]
This is something I've wanted to have on multiple occasions now. I've spent a few minutes crawling through the code but I have no experience with Kotlin or Android apps so I wasn't able to find where something like this would be implemented.

It could just be a new option in the node list's filter/options drop-down to alert on new nodes, defaulting to off, and persisting whatever state the user selects through restarts of the app.
