### ISSUE TITLE
GPS position shown as values close to 0,0 when node has no gps position but GPS precision is set to LOW_PRECISION or MEDIUM_PRECISION

### ISSUE THREAD

**Issue by Pscope** [meshtastic/Meshtastic-Android#918]
Tested in Android App Version 2.3.0. 

If a node is configured on the primary channel with either LOW_PRECISION or MEDIUM_PRECISION, this appears to set the GPS POSITON to 0.10486,0.10486  or  0.00328,0.00328 respectively and is shown in the node list and on the map. 

If HIGH_PRECISION is set when no GPS POSITION is given the node position is 0,0 and so is not show in the node list or on the map.

Maybe the app could also ignore 0.00328,0.00328 and 0.10486,0.10486 as thease are not generally valid positions of a node?

In this example, both nodes have no GPS position, 'PS3P' is set to MEDIUM_PRECISION, 'PS4P' is set to LOW_PRECISION on Primary channel  
![Null Node positions](https://github.com/meshtastic/Meshtastic-Android/assets/38895177/f79fd96f-76c7-4eeb-9419-0bb5c7ed9935)

**Comment by GMart** [comment]
I believe this was fixed with this change: https://github.com/meshtastic/firmware/pull/3325
Are all of those nodes updates to 2.3.0+?

**Comment by Pscope** [comment]
Yes, all on 2.3.0+ now. and after getting a GPS position and then loosing it again ( indoors) the position is no longer showing incorrect values.  Looks to be resolved now Thanks.
