### ISSUE TITLE
[Bug] Trying to change fixed position coords fails

### ISSUE THREAD

**Issue by prokrypt** [meshtastic/Meshtastic-Android#930]
Similar problem as https://github.com/meshtastic/python/issues/525 due to https://github.com/meshtastic/firmware/pull/3403

Fixed position must be disabled (with a node reboot) and then re-enabled with the new coordinates or otherwise they won't stick.

Possible solution (don't know how the android app sets position) is to have it automagically disable fixed position before setting location and re-enabling? If that's not possible then maybe gray out the input boxes when fixed position has already been set.

**Comment by garthvh** [comment]
You can't set a fixed position while fixed position is enabled anymore.

**Comment by jane1e** [comment]
why?

**Comment by prokrypt** [comment]
> why?

Because someone complained about phone-provided location overriding fixed position coordinates.
?!?

**Comment by joneyes** [comment]
> > why?
> 
> Because someone complained about phone-provided location overwriting fixed position coordinates. ?!?

The way around this would be to make provide phone location to mesh check box always visible (rather than only after device selection), that way you know the status before selecting the device
