### ISSUE TITLE
[ISSUE] Channel Config not reading previous state of channel (2.3.1)

### ISSUE THREAD

**Issue by ayysasha** [meshtastic/Meshtastic-Android#932]
https://github.com/meshtastic/Meshtastic-Android/assets/19575937/023a98da-2bb7-4271-8673-02d104057d19

Vers. 3.2.1

As shown in the video, the previous state of the Channel's location precision preference is not persisted/displayed to the user.

**Comment by prokrypt** [comment]
Your firmware is 2.2.23. Position precision was added in 2.2.24.

**Comment by ayysasha** [comment]
@prokrypt Great catch thank you, closing
