### ISSUE TITLE
Messages from multiple channels are merged together when switching between Meshtastic devices with different channel configurations

### ISSUE THREAD

**Issue by David-Woodward** [meshtastic/Meshtastic-Android#934]
When using an android phone with multiple Meshtastic devices that have different channel configurations, the messages are synced to channels on the phone based on channel index.

For example, channel index 0 on Meshtastic device #1 is "LongFast" and channel index 0 on Meshtastic device #2 is "Private."  If a single Android phone syncs to both of these Meshtastic devices, the android phone will show messages from both "LongFast" and "Private" mixed together in the channel at index 0.

Can messages be synced to the android phone into channels identified by the name/key combination instead of the channel index on the Meshtastic device?  If I'm not mistaken, this is the same logic used in the underlying Meshtastic protocols for identifying which channel a message belongs to, right?

**Comment by andrekir** [comment]
switching between devices is not supported, but there is an open feature request at #869
