### ISSUE TITLE
Match features/functions with iOS

### ISSUE THREAD

**Issue by lucidnx** [meshtastic/Meshtastic-Android#938]
Hello! I would like to see identical features in both apps, maybe in desktop management client too, can you cooperate with iOS devs to bring features from there to Android app and opposite?
Some kind of cooperation would be nice and help people aswell.

**Comment by francisuk1989** [comment]
We are missing lots of feature compared to the iOS.

https://github.com/meshtastic/Meshtastic-Android/issues/922

**Comment by thebentern** [comment]
This issue is too broad in scope. I suggest if you have some individual features you would like to see on either side, you can open those independently. There are different developers on both platforms, so keep in mind that it's dependent on their time and interest level.
