### ISSUE TITLE
Missbehaving text box for the channels PSK

### ISSUE THREAD

**Issue by 2E0RPT** [meshtastic/Meshtastic-Android#944]
When creating/copying a channels encryption key the Meshtastic app sometimes changes what you have inputted into the PSK text box,
For example (and you wont need to save/send it): If you goto Radio configuration > Channels > Click the {+} > In the PSK textbox type (Without correcting it) "noediting" you will see "ngediting==" (Please note the first two letters).

I understand the = or == padding because a certain number of bytes are required, But why does it change what im typing while im still typing it, I have never come accross any other PSK/Password input that does that.

**Comment by devop-mike** [comment]
The android app must be base64 decoding and then base64 encoding on each character entered.

In bash:-
`for c in n{f..w}==; do echo "${c} becomes $(echo "${c}" | base64 -d | base64)"; done`
Outputs:-
```
nf== becomes nQ==
ng== becomes ng==
nh== becomes ng==
ni== becomes ng==
nj== becomes ng==
nk== becomes ng==
nl== becomes ng==
nm== becomes ng==
nn== becomes ng==
no== becomes ng==
np== becomes ng==
nq== becomes ng==
nr== becomes ng==
ns== becomes ng==
nt== becomes ng==
nu== becomes ng==
nv== becomes ng==
nw== becomes nw==
```


In python
```
import base64

encoded_string = "no=="
decoded_string = base64.b64decode(encoded_string)
reencoded_string = base64.b64encode(decoded_string)
print(reencoded_string.decode('utf8'))
```
Outputs:-
`ng==`



Recommendations:-
1. Debounce the input field to give user time to enter string.
2. Only validate before submit.
