### ISSUE TITLE
IP Connection Non Stop Reloading with Android 2.3.3 alpha

### ISSUE THREAD

**Issue by nconder** [meshtastic/Meshtastic-Android#960]
[Meshtastic Android 2.3.3 alpha](https://github.com/meshtastic/Meshtastic-Android/releases/tag/2.3.3)

I have a LILYGO T-Beam firmware 2.2.7.e897ad setup as a router client that I connect to with an IP address over wifi and it sends MQTT.  The device is working as expected and works fine with other nodes.

When connecting over IP with android it connects quickly loads the modules then disconnects constantly repeats over and over again.

**Comment by andrekir** [comment]
you have multiple clients connecting to the radio at the same time. only one connection at a time is supported.
