### ISSUE TITLE
[Feature Request]: Adding the Restart & Shutdown commands to list of devices

### ISSUE THREAD

**Issue by SorenTheSwede** [meshtastic/Meshtastic-Android#962]
Hi all,

I've been using Meshtastic off and on for about a year, and I think a useful enhancement of the Android app would be to add the ability to restart and/or shutdown a device straight from the main list of devices rather than having to navigate from the device list to the Radio Configuration to do so.

Having the shutdown and/or restart commands on the device list would be especially handy if you want to restart or shutdown several devices at the same time.

A secondary request (and this should perhaps be a separate Feature Request) would be the option to have a "Kill All" option, meaning that a user can shut down multiple devices connected to their phone, if they have an urgent need to shut down multiple devices they control in a network (in case of a network breach, etc.).

I understand that Meshtastic only allows us to control one device at the time, but what I propose is that a "Kill All" command sends the shutdown command to the device you are currently connected to, then automatically cycles to the next device in the device list and repeats the shutdown, and so on, without the user having to do it manually for each device. It would probably be a good idea to limit the amount of time the app wants to use to automatically connect to each device before it gives up and moves onto the next device in the list.

Thank you for your great work!

**Comment by andrekir** [comment]
shutdown/reboot buttons used to be on the node list menu but got moved to the radio config to avoid accidental clicks. no plan to revert that or add bulk shutdown/reboot.
