### ISSUE TITLE
Move the "Forget Node" option 

### ISSUE THREAD

**Issue by GMart** [meshtastic/Meshtastic-Android#964]
The new ability to delete a node from the NodeDB is greatly appreciated. 
However I think it would make more sense in the list of options if it was below the "Ignore" option, instead of between Request Position and Traceroute. 
Also, it would be great to have a confirmation dialog before it deletes the node, since that's a permanent action on the NodeDB (At least until the node appears broadcasts again, if its in range)

**Comment by DayleDrinkwater** [comment]
Seems fair, I've put the changes together and I'll put in a PR soon.

**Comment by capslockapocalypse** [comment]
+1 for this. 
Constantly forgetting nodes instead of running a traceroute.
