### ISSUE TITLE
[Feature] Add ability to change channel index

### ISSUE THREAD

**Issue by djripcord** [meshtastic/Meshtastic-Android#965]
A really convenient feature would be the ability to change channel index on the fly without the need to remove existing channels. On the android app, it seems the default behavior when adding a channel is to replace the current primary. This is problematic because it causes confusion when sharing channels with others. Especially if they're new to Meshtastic, or don't realize what happens to the channels when adding.

At the very least, if it's problematic to change channel index on the fly, we should be able to choose the channel index number when adding a channel. That would at least eliminate the primary channel replacement issue.

I also know it is mentioned in the [documentation](https://meshtastic.org/docs/configuration/radio/channels/) that indexing cannot be modified. But the meaning of this is vague. I assume this statement means that indexing cannot be changed from the standard 0-7 slot numbers. Or am I incorrect in that assumption and this is a limitation of the meshtastic firmware?

**Comment by garthvh** [comment]
Channels don't use index other than in client apps, it is not sent over the mesh.

**Comment by djripcord** [comment]
> Channels don't use index other than in client apps, it is not sent over the mesh.

This is not a request to change how data is sent over the network. It is a request to add the ability to change or swap the primary channel for a secondary. For background node discovery via automatic telemetry reports, LongFast should be the primary channel. But if a user wishes to use a different channel for telemetry, it should be easier to do so. Just try adding a new channel to a node. You will see it puts LongFast to secondary and the new channel is set to primary.

I think we should be able to choose whether or not to set a new channel as a primary upon it's creation or import.

**Comment by andrekir** [comment]
long-press drag and drop was added to the channel editor in 2.3.14
