### ISSUE TITLE
[Feature request]: Display uptime (seconds) in the UI

### ISSUE THREAD

**Issue by thebentern** [meshtastic/Meshtastic-Android#971]
Sister ticket to https://github.com/meshtastic/Meshtastic-Apple/issues/603

As of 2.3.5 in the firmware, in the device telemetry packet, we now have an uptime in seconds metric value that can be displayed in the clients to allow users to see how long a node has been running since the last boot.

**Comment by asjmcguire** [comment]
Just needs a detailed node info screen now - because we can't just keep shoving everything in the nodelist ;)

**Comment by DayleDrinkwater** [comment]
Currently working on a node details screen, it'll be added in to thst
