### ISSUE TITLE
User-friendly region selection

### ISSUE THREAD

**Issue by AndreiRegiani** [meshtastic/Meshtastic-Android#987]
The initial setup can be more friendly by displaying country names in the region selection:

**ACTUAL**

<img width="172" alt="image" src="https://github.com/meshtastic/Meshtastic-Android/assets/1467605/965110aa-15e1-4802-bed1-202c403895f4">

---

**EXPECTED**
Code + country name, as shown in the official documentation:

<img width="359" alt="image" src="https://github.com/meshtastic/Meshtastic-Android/assets/1467605/acc10efe-374d-4df6-9c46-2dedbfc6ac09">

**Comment by AndreiRegiani** [comment]
>ANZ(RegionCode.ANZ, "Australia / New Zealand", 915.0f, 928.0f),

Could we add `Brazil` too? it's the same frequency, and has a big community.

https://meshtastic.org/docs/configuration/region-by-country/

**Comment by andrekir** [comment]
Brazil uses ANZ similar to how Canada and other countries use US for their frequency plans. The description reflects the primary regulatory region, not an exhaustive list of countries using it.
