### ISSUE TITLE
[Bug] connected node name inherits "(MQTT)"

### ISSUE THREAD

**Issue by prokrypt** [meshtastic/Meshtastic-Android#989]
Hopefully the screenshots are self-explanatory...
This happened after switching over from another node that saw "Cake" through mqtt

![Screenshot_20240422-021735-479](https://github.com/meshtastic/Meshtastic-Android/assets/1832555/230f3ca3-cd48-4c53-b5c7-18ad2203f86f)
![Screenshot_20240422-021755-610](https://github.com/meshtastic/Meshtastic-Android/assets/1832555/4300c230-5fce-4dc2-9ac4-c3f7d3eddf67)
![Screenshot_20240422-021810-206](https://github.com/meshtastic/Meshtastic-Android/assets/1832555/5521fd9c-ea73-43c9-ab89-d21154b243dc)

**Comment by andrekir** [comment]
all information comes from the radio. look for the Nodeinfo log for your local node in the debug panel right after the connection handshake. does it have `via_mqtt` tagged as true?

that's the only way this could be happening. the nodeDB is wipped between reconnects.
