### ISSUE TITLE
battery level 0 in protobuf should render as "battery level unknown"

### ISSUE THREAD

**Issue by geeksville** [meshtastic/Meshtastic-Android#99]
more info here: https://meshtastic.discourse.group/t/alpha-tester-thread-no-new-tests-needed-at-the-moment/298/189?u=geeksville

**Comment by geeksville** [comment]
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/alpha-tester-thread-no-new-tests-needed-at-the-moment/298/189

**Comment by lgoix** [comment]
A charging icon could be displayed
